// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: room_chat.proto

package protoc

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ROOM_CHAT_MSG_TYPE int32

const (
	ROOM_CHAT_MSG_TYPE_RCM_DEFAULT                   ROOM_CHAT_MSG_TYPE = 0
	ROOM_CHAT_MSG_TYPE_RCM_CHAT_REQUEST              ROOM_CHAT_MSG_TYPE = 2001
	ROOM_CHAT_MSG_TYPE_RCM_CHAT_RESPONSE             ROOM_CHAT_MSG_TYPE = 2005
	ROOM_CHAT_MSG_TYPE_RCM_CHAT_DATA                 ROOM_CHAT_MSG_TYPE = 2010
	ROOM_CHAT_MSG_TYPE_RCM_LAST_CHATS_DATA           ROOM_CHAT_MSG_TYPE = 2020
	ROOM_CHAT_MSG_TYPE_RCM_QUERY_LAST_CHATS_REQUEST  ROOM_CHAT_MSG_TYPE = 2030
	ROOM_CHAT_MSG_TYPE_RCM_QUERY_LAST_CHATS_RESPONSE ROOM_CHAT_MSG_TYPE = 2040
	ROOM_CHAT_MSG_TYPE_RCM_BEGIN_VOICE_REQUEST       ROOM_CHAT_MSG_TYPE = 2050
	ROOM_CHAT_MSG_TYPE_RCM_BEGIN_VOICE_RESPONSE      ROOM_CHAT_MSG_TYPE = 2060
	ROOM_CHAT_MSG_TYPE_RCM_BEGIN_VOICE_COMMAND       ROOM_CHAT_MSG_TYPE = 2065
	ROOM_CHAT_MSG_TYPE_RCM_END_VOICE_REQUEST         ROOM_CHAT_MSG_TYPE = 2070
	ROOM_CHAT_MSG_TYPE_RCM_END_VOICE_RESPONSE        ROOM_CHAT_MSG_TYPE = 2090
	ROOM_CHAT_MSG_TYPE_RCM_END_VOICE_COMMAND         ROOM_CHAT_MSG_TYPE = 2095
	ROOM_CHAT_MSG_TYPE_RCM_AT_COMMAND                ROOM_CHAT_MSG_TYPE = 2100
	ROOM_CHAT_MSG_TYPE_RCM_SECRET_CHAT_REQUEST       ROOM_CHAT_MSG_TYPE = 2110
	ROOM_CHAT_MSG_TYPE_RCM_SECRET_CHAT_RESPONSE      ROOM_CHAT_MSG_TYPE = 2120
	ROOM_CHAT_MSG_TYPE_RCM_SECRET_CHAT_DATA          ROOM_CHAT_MSG_TYPE = 2130
)

var ROOM_CHAT_MSG_TYPE_name = map[int32]string{
	0:    "RCM_DEFAULT",
	2001: "RCM_CHAT_REQUEST",
	2005: "RCM_CHAT_RESPONSE",
	2010: "RCM_CHAT_DATA",
	2020: "RCM_LAST_CHATS_DATA",
	2030: "RCM_QUERY_LAST_CHATS_REQUEST",
	2040: "RCM_QUERY_LAST_CHATS_RESPONSE",
	2050: "RCM_BEGIN_VOICE_REQUEST",
	2060: "RCM_BEGIN_VOICE_RESPONSE",
	2065: "RCM_BEGIN_VOICE_COMMAND",
	2070: "RCM_END_VOICE_REQUEST",
	2090: "RCM_END_VOICE_RESPONSE",
	2095: "RCM_END_VOICE_COMMAND",
	2100: "RCM_AT_COMMAND",
	2110: "RCM_SECRET_CHAT_REQUEST",
	2120: "RCM_SECRET_CHAT_RESPONSE",
	2130: "RCM_SECRET_CHAT_DATA",
}

var ROOM_CHAT_MSG_TYPE_value = map[string]int32{
	"RCM_DEFAULT":                   0,
	"RCM_CHAT_REQUEST":              2001,
	"RCM_CHAT_RESPONSE":             2005,
	"RCM_CHAT_DATA":                 2010,
	"RCM_LAST_CHATS_DATA":           2020,
	"RCM_QUERY_LAST_CHATS_REQUEST":  2030,
	"RCM_QUERY_LAST_CHATS_RESPONSE": 2040,
	"RCM_BEGIN_VOICE_REQUEST":       2050,
	"RCM_BEGIN_VOICE_RESPONSE":      2060,
	"RCM_BEGIN_VOICE_COMMAND":       2065,
	"RCM_END_VOICE_REQUEST":         2070,
	"RCM_END_VOICE_RESPONSE":        2090,
	"RCM_END_VOICE_COMMAND":         2095,
	"RCM_AT_COMMAND":                2100,
	"RCM_SECRET_CHAT_REQUEST":       2110,
	"RCM_SECRET_CHAT_RESPONSE":      2120,
	"RCM_SECRET_CHAT_DATA":          2130,
}

func (x ROOM_CHAT_MSG_TYPE) String() string {
	return proto.EnumName(ROOM_CHAT_MSG_TYPE_name, int32(x))
}

func (ROOM_CHAT_MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{0}
}

type ChatRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatRequest) Reset()         { *m = ChatRequest{} }
func (m *ChatRequest) String() string { return proto.CompactTextString(m) }
func (*ChatRequest) ProtoMessage()    {}
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{0}
}
func (m *ChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatRequest.Unmarshal(m, b)
}
func (m *ChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatRequest.Marshal(b, m, deterministic)
}
func (m *ChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatRequest.Merge(m, src)
}
func (m *ChatRequest) XXX_Size() int {
	return xxx_messageInfo_ChatRequest.Size(m)
}
func (m *ChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChatRequest proto.InternalMessageInfo

func (m *ChatRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ChatRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ChatData struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int32    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attachment           []byte   `protobuf:"bytes,3,opt,name=attachment,proto3" json:"attachment,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Lang                 string   `protobuf:"bytes,8,opt,name=lang,proto3" json:"lang,omitempty"`
	Id                   string   `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatData) Reset()         { *m = ChatData{} }
func (m *ChatData) String() string { return proto.CompactTextString(m) }
func (*ChatData) ProtoMessage()    {}
func (*ChatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{1}
}
func (m *ChatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatData.Unmarshal(m, b)
}
func (m *ChatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatData.Marshal(b, m, deterministic)
}
func (m *ChatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatData.Merge(m, src)
}
func (m *ChatData) XXX_Size() int {
	return xxx_messageInfo_ChatData.Size(m)
}
func (m *ChatData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatData.DiscardUnknown(m)
}

var xxx_messageInfo_ChatData proto.InternalMessageInfo

func (m *ChatData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ChatData) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChatData) GetAttachment() []byte {
	if m != nil {
		return m.Attachment
	}
	return nil
}

func (m *ChatData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChatData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ChatData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatData) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *ChatData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SecretChatRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretChatRequest) Reset()         { *m = SecretChatRequest{} }
func (m *SecretChatRequest) String() string { return proto.CompactTextString(m) }
func (*SecretChatRequest) ProtoMessage()    {}
func (*SecretChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{2}
}
func (m *SecretChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretChatRequest.Unmarshal(m, b)
}
func (m *SecretChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretChatRequest.Marshal(b, m, deterministic)
}
func (m *SecretChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretChatRequest.Merge(m, src)
}
func (m *SecretChatRequest) XXX_Size() int {
	return xxx_messageInfo_SecretChatRequest.Size(m)
}
func (m *SecretChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretChatRequest proto.InternalMessageInfo

func (m *SecretChatRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SecretChatRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SecretChatRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LastChatsData struct {
	Chats                []*ChatData `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LastChatsData) Reset()         { *m = LastChatsData{} }
func (m *LastChatsData) String() string { return proto.CompactTextString(m) }
func (*LastChatsData) ProtoMessage()    {}
func (*LastChatsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{3}
}
func (m *LastChatsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastChatsData.Unmarshal(m, b)
}
func (m *LastChatsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastChatsData.Marshal(b, m, deterministic)
}
func (m *LastChatsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastChatsData.Merge(m, src)
}
func (m *LastChatsData) XXX_Size() int {
	return xxx_messageInfo_LastChatsData.Size(m)
}
func (m *LastChatsData) XXX_DiscardUnknown() {
	xxx_messageInfo_LastChatsData.DiscardUnknown(m)
}

var xxx_messageInfo_LastChatsData proto.InternalMessageInfo

func (m *LastChatsData) GetChats() []*ChatData {
	if m != nil {
		return m.Chats
	}
	return nil
}

type VoiceData struct {
	Chats                []*ChatData `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VoiceData) Reset()         { *m = VoiceData{} }
func (m *VoiceData) String() string { return proto.CompactTextString(m) }
func (*VoiceData) ProtoMessage()    {}
func (*VoiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{4}
}
func (m *VoiceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceData.Unmarshal(m, b)
}
func (m *VoiceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceData.Marshal(b, m, deterministic)
}
func (m *VoiceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceData.Merge(m, src)
}
func (m *VoiceData) XXX_Size() int {
	return xxx_messageInfo_VoiceData.Size(m)
}
func (m *VoiceData) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceData.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceData proto.InternalMessageInfo

func (m *VoiceData) GetChats() []*ChatData {
	if m != nil {
		return m.Chats
	}
	return nil
}

type EndVoiceCommand struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndVoiceCommand) Reset()         { *m = EndVoiceCommand{} }
func (m *EndVoiceCommand) String() string { return proto.CompactTextString(m) }
func (*EndVoiceCommand) ProtoMessage()    {}
func (*EndVoiceCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{5}
}
func (m *EndVoiceCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndVoiceCommand.Unmarshal(m, b)
}
func (m *EndVoiceCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndVoiceCommand.Marshal(b, m, deterministic)
}
func (m *EndVoiceCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndVoiceCommand.Merge(m, src)
}
func (m *EndVoiceCommand) XXX_Size() int {
	return xxx_messageInfo_EndVoiceCommand.Size(m)
}
func (m *EndVoiceCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_EndVoiceCommand.DiscardUnknown(m)
}

var xxx_messageInfo_EndVoiceCommand proto.InternalMessageInfo

func (m *EndVoiceCommand) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type BeginVoiceCommand struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginVoiceCommand) Reset()         { *m = BeginVoiceCommand{} }
func (m *BeginVoiceCommand) String() string { return proto.CompactTextString(m) }
func (*BeginVoiceCommand) ProtoMessage()    {}
func (*BeginVoiceCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{6}
}
func (m *BeginVoiceCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginVoiceCommand.Unmarshal(m, b)
}
func (m *BeginVoiceCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginVoiceCommand.Marshal(b, m, deterministic)
}
func (m *BeginVoiceCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginVoiceCommand.Merge(m, src)
}
func (m *BeginVoiceCommand) XXX_Size() int {
	return xxx_messageInfo_BeginVoiceCommand.Size(m)
}
func (m *BeginVoiceCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginVoiceCommand.DiscardUnknown(m)
}

var xxx_messageInfo_BeginVoiceCommand proto.InternalMessageInfo

func (m *BeginVoiceCommand) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AtCommand struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FromUserId           string   `protobuf:"bytes,2,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	FromUserName         string   `protobuf:"bytes,3,opt,name=fromUserName,proto3" json:"fromUserName,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AtCommand) Reset()         { *m = AtCommand{} }
func (m *AtCommand) String() string { return proto.CompactTextString(m) }
func (*AtCommand) ProtoMessage()    {}
func (*AtCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c4c4bd5d212dea, []int{7}
}
func (m *AtCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtCommand.Unmarshal(m, b)
}
func (m *AtCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtCommand.Marshal(b, m, deterministic)
}
func (m *AtCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtCommand.Merge(m, src)
}
func (m *AtCommand) XXX_Size() int {
	return xxx_messageInfo_AtCommand.Size(m)
}
func (m *AtCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AtCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AtCommand proto.InternalMessageInfo

func (m *AtCommand) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AtCommand) GetFromUserId() string {
	if m != nil {
		return m.FromUserId
	}
	return ""
}

func (m *AtCommand) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

func (m *AtCommand) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AtCommand) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("protoc.ROOM_CHAT_MSG_TYPE", ROOM_CHAT_MSG_TYPE_name, ROOM_CHAT_MSG_TYPE_value)
	proto.RegisterType((*ChatRequest)(nil), "protoc.ChatRequest")
	proto.RegisterType((*ChatData)(nil), "protoc.ChatData")
	proto.RegisterType((*SecretChatRequest)(nil), "protoc.SecretChatRequest")
	proto.RegisterType((*LastChatsData)(nil), "protoc.LastChatsData")
	proto.RegisterType((*VoiceData)(nil), "protoc.VoiceData")
	proto.RegisterType((*EndVoiceCommand)(nil), "protoc.EndVoiceCommand")
	proto.RegisterType((*BeginVoiceCommand)(nil), "protoc.BeginVoiceCommand")
	proto.RegisterType((*AtCommand)(nil), "protoc.AtCommand")
}

func init() { proto.RegisterFile("room_chat.proto", fileDescriptor_25c4c4bd5d212dea) }

var fileDescriptor_25c4c4bd5d212dea = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xb1, 0x6f, 0xd3, 0x50,
	0x10, 0xc6, 0x71, 0xd2, 0xb4, 0xf5, 0xa5, 0xad, 0x5f, 0xaf, 0xb4, 0x98, 0xd2, 0xa2, 0xe0, 0x01,
	0x05, 0x90, 0x82, 0x44, 0x07, 0x66, 0xd7, 0x79, 0x94, 0x4a, 0x4d, 0xd2, 0xda, 0x4e, 0xa5, 0xb2,
	0x58, 0x0f, 0xc7, 0xb4, 0x91, 0xb0, 0x5d, 0xec, 0x17, 0xfe, 0x00, 0x66, 0x16, 0x16, 0x76, 0x56,
	0x16, 0x16, 0x66, 0x66, 0xc4, 0x06, 0x12, 0x0b, 0x33, 0x62, 0x64, 0x66, 0x44, 0xef, 0x39, 0x36,
	0x4e, 0x28, 0x82, 0x4a, 0x4c, 0x79, 0xf7, 0xfb, 0xee, 0xbe, 0xbb, 0xdc, 0x29, 0x01, 0x2d, 0x89,
	0xe3, 0xd0, 0xf3, 0x4f, 0x18, 0x6f, 0x9d, 0x26, 0x31, 0x8f, 0x71, 0x56, 0x7e, 0xf8, 0x06, 0x85,
	0xba, 0x75, 0xc2, 0xb8, 0x1d, 0x3c, 0x19, 0x05, 0x29, 0x47, 0x1d, 0xe6, 0xfc, 0x38, 0xe2, 0x41,
	0xc4, 0x75, 0xa5, 0xa1, 0x34, 0x55, 0x3b, 0x0f, 0x71, 0x03, 0x54, 0x3e, 0x0c, 0x83, 0x94, 0xb3,
	0xf0, 0x54, 0xaf, 0x34, 0x94, 0x66, 0xd5, 0xfe, 0x05, 0x8c, 0x0f, 0x0a, 0xcc, 0x0b, 0x9f, 0x36,
	0xe3, 0xec, 0x3c, 0x26, 0xb5, 0x92, 0x09, 0x5e, 0x05, 0x60, 0x9c, 0x33, 0xff, 0x24, 0x14, 0xa5,
	0xd5, 0x86, 0xd2, 0x5c, 0xb0, 0x4b, 0x04, 0xd7, 0x60, 0x76, 0x94, 0x06, 0xc9, 0xee, 0x40, 0x9f,
	0x91, 0xb6, 0xe3, 0x48, 0x70, 0xf6, 0x94, 0x71, 0x96, 0xe8, 0xb5, 0x8c, 0x67, 0x11, 0x22, 0xcc,
	0x44, 0x2c, 0x0c, 0xf4, 0x39, 0x49, 0xe5, 0x5b, 0xb0, 0xc7, 0x2c, 0x3a, 0xd6, 0xe7, 0x33, 0x26,
	0xde, 0xb8, 0x04, 0x95, 0xe1, 0x40, 0x57, 0x25, 0xa9, 0x0c, 0x07, 0x86, 0x0f, 0xcb, 0x4e, 0xe0,
	0x27, 0x01, 0xff, 0x0f, 0x9b, 0x29, 0x0d, 0x5d, 0x2d, 0x0f, 0x6d, 0xdc, 0x85, 0xc5, 0x3d, 0x96,
	0xca, 0x16, 0xa9, 0xdc, 0xda, 0x75, 0xa8, 0x89, 0xfb, 0xa4, 0xba, 0xd2, 0xa8, 0x36, 0xeb, 0x77,
	0x48, 0x76, 0x28, 0xbf, 0x95, 0xaf, 0xd5, 0xce, 0x64, 0x63, 0x0b, 0xd4, 0xc3, 0x78, 0xe8, 0x07,
	0xe7, 0x2a, 0xba, 0x01, 0x1a, 0x8d, 0x06, 0xb2, 0xce, 0x8a, 0xc3, 0x90, 0x45, 0x83, 0xd2, 0x60,
	0xca, 0xc4, 0x60, 0xb7, 0x60, 0x79, 0x3b, 0x38, 0x1e, 0x46, 0xff, 0x94, 0xfc, 0x4a, 0x01, 0xd5,
	0xe4, 0x7f, 0xc9, 0x12, 0x87, 0x7d, 0x94, 0xc4, 0x61, 0x3f, 0xd3, 0x2a, 0x52, 0x2b, 0x11, 0x34,
	0x60, 0x21, 0x8f, 0xba, 0xe2, 0x60, 0xd9, 0xa6, 0x26, 0x18, 0xae, 0xc3, 0xfc, 0x28, 0xd7, 0xb3,
	0xf3, 0x17, 0xf1, 0xe4, 0x05, 0x6a, 0x53, 0x17, 0xb8, 0xf9, 0xad, 0x0a, 0x68, 0xf7, 0x7a, 0x1d,
	0xcf, 0xba, 0x6f, 0xba, 0x5e, 0xc7, 0xd9, 0xf1, 0xdc, 0xa3, 0x7d, 0x8a, 0x1a, 0xd4, 0x6d, 0xab,
	0xe3, 0xb5, 0xe9, 0x3d, 0xb3, 0xbf, 0xe7, 0x92, 0x0b, 0xb8, 0x0a, 0x44, 0x00, 0x99, 0x65, 0xd3,
	0x83, 0x3e, 0x75, 0x5c, 0xf2, 0x51, 0xc3, 0x35, 0x58, 0x2e, 0x61, 0x67, 0xbf, 0xd7, 0x75, 0x28,
	0xf9, 0xac, 0x21, 0xc2, 0x62, 0xc1, 0xdb, 0xa6, 0x6b, 0x92, 0x2f, 0x1a, 0xea, 0xb0, 0x22, 0xd8,
	0x9e, 0xe9, 0xb8, 0x52, 0x70, 0x32, 0xe5, 0xab, 0x86, 0xd7, 0x60, 0x43, 0x28, 0x07, 0x7d, 0x6a,
	0x1f, 0x95, 0xf5, 0xbc, 0xd1, 0x77, 0x0d, 0x0d, 0xd8, 0xfc, 0x43, 0xca, 0xb8, 0xe9, 0x0f, 0x0d,
	0x37, 0xe0, 0x92, 0xc8, 0xd9, 0xa6, 0x3b, 0xbb, 0x5d, 0xef, 0xb0, 0xb7, 0x6b, 0xd1, 0xc2, 0xe1,
	0x19, 0xc1, 0x4d, 0xd0, 0x7f, 0x57, 0xc7, 0xc5, 0xcf, 0xc9, 0x59, 0xc5, 0x56, 0xaf, 0xd3, 0x31,
	0xbb, 0x6d, 0xf2, 0x82, 0xe0, 0x3a, 0xac, 0x0a, 0x95, 0x76, 0xdb, 0x53, 0xc6, 0x2f, 0x09, 0x5e,
	0x81, 0xb5, 0x69, 0x6d, 0x6c, 0xfb, 0xfa, 0x8c, 0xc2, 0xdc, 0xf4, 0x0d, 0xc1, 0x15, 0x58, 0x12,
	0x9a, 0xe9, 0x16, 0xf0, 0x6d, 0x31, 0x87, 0x43, 0x2d, 0x9b, 0xba, 0x93, 0xfb, 0x7e, 0x57, 0x7c,
	0x89, 0x49, 0x75, 0xdc, 0xed, 0x3d, 0xc1, 0xcb, 0x70, 0x71, 0x5a, 0x96, 0x3b, 0xfe, 0x44, 0xb6,
	0xeb, 0x0f, 0xd4, 0x56, 0xeb, 0x76, 0xf6, 0x0b, 0x78, 0x98, 0xfd, 0xc1, 0x6d, 0xfd, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0x01, 0xb9, 0x6d, 0x0f, 0xfa, 0x04, 0x00, 0x00,
}
