// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: room.proto

package protoc

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//进入第一个房间
//列出房间列表
//进入选定房间
//邀请account进入房间
//列出关注列表
//退出房间
//永远都有一个房间
type ROOM_MSG_TYPE int32

const (
	ROOM_MSG_TYPE_RM_DEFAULT                       ROOM_MSG_TYPE = 0
	ROOM_MSG_TYPE_RM_KEEP_ALIVE                    ROOM_MSG_TYPE = 1
	ROOM_MSG_TYPE_RM_ENTER_REQUEST                 ROOM_MSG_TYPE = 1001
	ROOM_MSG_TYPE_RM_ENTER_RESPONSE                ROOM_MSG_TYPE = 1005
	ROOM_MSG_TYPE_RM_ENTER_ROOM_COMMAND            ROOM_MSG_TYPE = 1010
	ROOM_MSG_TYPE_RM_QUERY_ROOM_REQUEST            ROOM_MSG_TYPE = 1020
	ROOM_MSG_TYPE_RM_QUERY_ROOM_RESPONSE           ROOM_MSG_TYPE = 1025
	ROOM_MSG_TYPE_RM_ROOM_DATA                     ROOM_MSG_TYPE = 1030
	ROOM_MSG_TYPE_RM_ROOM_PLAYER_DATA              ROOM_MSG_TYPE = 1040
	ROOM_MSG_TYPE_RM_ROOM_POSITION_DATA            ROOM_MSG_TYPE = 1050
	ROOM_MSG_TYPE_RM_LIST_ROOM_REQUEST             ROOM_MSG_TYPE = 1060
	ROOM_MSG_TYPE_RM_LIST_ROOM_RESPONSE            ROOM_MSG_TYPE = 1065
	ROOM_MSG_TYPE_RM_CURRENT_ROOM_DATA             ROOM_MSG_TYPE = 1070
	ROOM_MSG_TYPE_RM_JOIN_ROOM_REQUEST             ROOM_MSG_TYPE = 1080
	ROOM_MSG_TYPE_RM_JOIN_ROOM_RESPONSE            ROOM_MSG_TYPE = 1085
	ROOM_MSG_TYPE_RM_INVITE_ROOM_COMMAND           ROOM_MSG_TYPE = 1090
	ROOM_MSG_TYPE_RM_INVITE_ROOM_REQUEST           ROOM_MSG_TYPE = 1095
	ROOM_MSG_TYPE_RM_INVITE_ROOM_RESPONSE          ROOM_MSG_TYPE = 1097
	ROOM_MSG_TYPE_RM_CREATE_ROOM_REQUEST           ROOM_MSG_TYPE = 1100
	ROOM_MSG_TYPE_RM_CREATE_ROOM_RESPONSE          ROOM_MSG_TYPE = 1110
	ROOM_MSG_TYPE_RM_QUIT_ROOM_REQUEST             ROOM_MSG_TYPE = 1120
	ROOM_MSG_TYPE_RM_QUIT_ROOM_RESPONSE            ROOM_MSG_TYPE = 1130
	ROOM_MSG_TYPE_RM_ROOM_MOVE_DATA                ROOM_MSG_TYPE = 1140
	ROOM_MSG_TYPE_RM_LOAD_READY_REQUEST            ROOM_MSG_TYPE = 1150
	ROOM_MSG_TYPE_RM_LOAD_READY_RESPONSE           ROOM_MSG_TYPE = 1160
	ROOM_MSG_TYPE_RM_KEEPALIVE_REQUEST             ROOM_MSG_TYPE = 1190
	ROOM_MSG_TYPE_RM_KEEPALIVE_RESPONSE            ROOM_MSG_TYPE = 1200
	ROOM_MSG_TYPE_RM_LOOK_REQUEST                  ROOM_MSG_TYPE = 1210
	ROOM_MSG_TYPE_RM_LOOK_RESPONSE                 ROOM_MSG_TYPE = 1220
	ROOM_MSG_TYPE_RM_LOOK_DATA                     ROOM_MSG_TYPE = 1230
	ROOM_MSG_TYPE_RM_SET_PASSWORD_REQUEST          ROOM_MSG_TYPE = 1240
	ROOM_MSG_TYPE_RM_SET_PASSWORD_RESPONSE         ROOM_MSG_TYPE = 1250
	ROOM_MSG_TYPE_RM_SET_ROOM_TYPE_REQUEST         ROOM_MSG_TYPE = 1260
	ROOM_MSG_TYPE_RM_SET_ROOM_TYPE_RESPONSE        ROOM_MSG_TYPE = 1270
	ROOM_MSG_TYPE_RM_PACK_DATA                     ROOM_MSG_TYPE = 1280
	ROOM_MSG_TYPE_RM_KICK_REQUEST                  ROOM_MSG_TYPE = 1290
	ROOM_MSG_TYPE_RM_KICK_RESPONSE                 ROOM_MSG_TYPE = 1300
	ROOM_MSG_TYPE_RM_KICK_COMMAND                  ROOM_MSG_TYPE = 1310
	ROOM_MSG_TYPE_RM_QUIT_COMMAND                  ROOM_MSG_TYPE = 1320
	ROOM_MSG_TYPE_RM_SET_ROOM_PUBLIC_TYPE_REQUEST  ROOM_MSG_TYPE = 1330
	ROOM_MSG_TYPE_RM_SET_ROOM_PUBLIC_TYPE_RESPONSE ROOM_MSG_TYPE = 1340
)

var ROOM_MSG_TYPE_name = map[int32]string{
	0:    "RM_DEFAULT",
	1:    "RM_KEEP_ALIVE",
	1001: "RM_ENTER_REQUEST",
	1005: "RM_ENTER_RESPONSE",
	1010: "RM_ENTER_ROOM_COMMAND",
	1020: "RM_QUERY_ROOM_REQUEST",
	1025: "RM_QUERY_ROOM_RESPONSE",
	1030: "RM_ROOM_DATA",
	1040: "RM_ROOM_PLAYER_DATA",
	1050: "RM_ROOM_POSITION_DATA",
	1060: "RM_LIST_ROOM_REQUEST",
	1065: "RM_LIST_ROOM_RESPONSE",
	1070: "RM_CURRENT_ROOM_DATA",
	1080: "RM_JOIN_ROOM_REQUEST",
	1085: "RM_JOIN_ROOM_RESPONSE",
	1090: "RM_INVITE_ROOM_COMMAND",
	1095: "RM_INVITE_ROOM_REQUEST",
	1097: "RM_INVITE_ROOM_RESPONSE",
	1100: "RM_CREATE_ROOM_REQUEST",
	1110: "RM_CREATE_ROOM_RESPONSE",
	1120: "RM_QUIT_ROOM_REQUEST",
	1130: "RM_QUIT_ROOM_RESPONSE",
	1140: "RM_ROOM_MOVE_DATA",
	1150: "RM_LOAD_READY_REQUEST",
	1160: "RM_LOAD_READY_RESPONSE",
	1190: "RM_KEEPALIVE_REQUEST",
	1200: "RM_KEEPALIVE_RESPONSE",
	1210: "RM_LOOK_REQUEST",
	1220: "RM_LOOK_RESPONSE",
	1230: "RM_LOOK_DATA",
	1240: "RM_SET_PASSWORD_REQUEST",
	1250: "RM_SET_PASSWORD_RESPONSE",
	1260: "RM_SET_ROOM_TYPE_REQUEST",
	1270: "RM_SET_ROOM_TYPE_RESPONSE",
	1280: "RM_PACK_DATA",
	1290: "RM_KICK_REQUEST",
	1300: "RM_KICK_RESPONSE",
	1310: "RM_KICK_COMMAND",
	1320: "RM_QUIT_COMMAND",
	1330: "RM_SET_ROOM_PUBLIC_TYPE_REQUEST",
	1340: "RM_SET_ROOM_PUBLIC_TYPE_RESPONSE",
}

var ROOM_MSG_TYPE_value = map[string]int32{
	"RM_DEFAULT":                       0,
	"RM_KEEP_ALIVE":                    1,
	"RM_ENTER_REQUEST":                 1001,
	"RM_ENTER_RESPONSE":                1005,
	"RM_ENTER_ROOM_COMMAND":            1010,
	"RM_QUERY_ROOM_REQUEST":            1020,
	"RM_QUERY_ROOM_RESPONSE":           1025,
	"RM_ROOM_DATA":                     1030,
	"RM_ROOM_PLAYER_DATA":              1040,
	"RM_ROOM_POSITION_DATA":            1050,
	"RM_LIST_ROOM_REQUEST":             1060,
	"RM_LIST_ROOM_RESPONSE":            1065,
	"RM_CURRENT_ROOM_DATA":             1070,
	"RM_JOIN_ROOM_REQUEST":             1080,
	"RM_JOIN_ROOM_RESPONSE":            1085,
	"RM_INVITE_ROOM_COMMAND":           1090,
	"RM_INVITE_ROOM_REQUEST":           1095,
	"RM_INVITE_ROOM_RESPONSE":          1097,
	"RM_CREATE_ROOM_REQUEST":           1100,
	"RM_CREATE_ROOM_RESPONSE":          1110,
	"RM_QUIT_ROOM_REQUEST":             1120,
	"RM_QUIT_ROOM_RESPONSE":            1130,
	"RM_ROOM_MOVE_DATA":                1140,
	"RM_LOAD_READY_REQUEST":            1150,
	"RM_LOAD_READY_RESPONSE":           1160,
	"RM_KEEPALIVE_REQUEST":             1190,
	"RM_KEEPALIVE_RESPONSE":            1200,
	"RM_LOOK_REQUEST":                  1210,
	"RM_LOOK_RESPONSE":                 1220,
	"RM_LOOK_DATA":                     1230,
	"RM_SET_PASSWORD_REQUEST":          1240,
	"RM_SET_PASSWORD_RESPONSE":         1250,
	"RM_SET_ROOM_TYPE_REQUEST":         1260,
	"RM_SET_ROOM_TYPE_RESPONSE":        1270,
	"RM_PACK_DATA":                     1280,
	"RM_KICK_REQUEST":                  1290,
	"RM_KICK_RESPONSE":                 1300,
	"RM_KICK_COMMAND":                  1310,
	"RM_QUIT_COMMAND":                  1320,
	"RM_SET_ROOM_PUBLIC_TYPE_REQUEST":  1330,
	"RM_SET_ROOM_PUBLIC_TYPE_RESPONSE": 1340,
}

func (x ROOM_MSG_TYPE) String() string {
	return proto.EnumName(ROOM_MSG_TYPE_name, int32(x))
}

func (ROOM_MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

type StandardResponse struct {
	ErrMsg               string   `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	RetCode              int32    `protobuf:"varint,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StandardResponse) Reset()         { *m = StandardResponse{} }
func (m *StandardResponse) String() string { return proto.CompactTextString(m) }
func (*StandardResponse) ProtoMessage()    {}
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}
func (m *StandardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandardResponse.Unmarshal(m, b)
}
func (m *StandardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandardResponse.Marshal(b, m, deterministic)
}
func (m *StandardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandardResponse.Merge(m, src)
}
func (m *StandardResponse) XXX_Size() int {
	return xxx_messageInfo_StandardResponse.Size(m)
}
func (m *StandardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StandardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StandardResponse proto.InternalMessageInfo

func (m *StandardResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *StandardResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

type StandardRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StandardRequest) Reset()         { *m = StandardRequest{} }
func (m *StandardRequest) String() string { return proto.CompactTextString(m) }
func (*StandardRequest) ProtoMessage()    {}
func (*StandardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}
func (m *StandardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandardRequest.Unmarshal(m, b)
}
func (m *StandardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandardRequest.Marshal(b, m, deterministic)
}
func (m *StandardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandardRequest.Merge(m, src)
}
func (m *StandardRequest) XXX_Size() int {
	return xxx_messageInfo_StandardRequest.Size(m)
}
func (m *StandardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StandardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StandardRequest proto.InternalMessageInfo

//一开始进入，发起请求
type EnterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRequest) Reset()         { *m = EnterRequest{} }
func (m *EnterRequest) String() string { return proto.CompactTextString(m) }
func (*EnterRequest) ProtoMessage()    {}
func (*EnterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}
func (m *EnterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRequest.Unmarshal(m, b)
}
func (m *EnterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRequest.Marshal(b, m, deterministic)
}
func (m *EnterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRequest.Merge(m, src)
}
func (m *EnterRequest) XXX_Size() int {
	return xxx_messageInfo_EnterRequest.Size(m)
}
func (m *EnterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRequest proto.InternalMessageInfo

//服务器通知客户端，加载资源，进入房间，目前就一个资源，无视resID直接加载就好
type EnterRoomCommand struct {
	RoomType             string   `protobuf:"bytes,2,opt,name=roomType,proto3" json:"roomType,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomResId            string   `protobuf:"bytes,4,opt,name=roomResId,proto3" json:"roomResId,omitempty"`
	RoomName             string   `protobuf:"bytes,5,opt,name=roomName,proto3" json:"roomName,omitempty"`
	RoomDescription      string   `protobuf:"bytes,6,opt,name=roomDescription,proto3" json:"roomDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRoomCommand) Reset()         { *m = EnterRoomCommand{} }
func (m *EnterRoomCommand) String() string { return proto.CompactTextString(m) }
func (*EnterRoomCommand) ProtoMessage()    {}
func (*EnterRoomCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}
func (m *EnterRoomCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomCommand.Unmarshal(m, b)
}
func (m *EnterRoomCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomCommand.Marshal(b, m, deterministic)
}
func (m *EnterRoomCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomCommand.Merge(m, src)
}
func (m *EnterRoomCommand) XXX_Size() int {
	return xxx_messageInfo_EnterRoomCommand.Size(m)
}
func (m *EnterRoomCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomCommand.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomCommand proto.InternalMessageInfo

func (m *EnterRoomCommand) GetRoomType() string {
	if m != nil {
		return m.RoomType
	}
	return ""
}

func (m *EnterRoomCommand) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *EnterRoomCommand) GetRoomResId() string {
	if m != nil {
		return m.RoomResId
	}
	return ""
}

func (m *EnterRoomCommand) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *EnterRoomCommand) GetRoomDescription() string {
	if m != nil {
		return m.RoomDescription
	}
	return ""
}

//服务器收到QueryRoom推送RoomData,有角色信息，客户端加载角色模型
type RoomData struct {
	RoomId               string                     `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomName             string                     `protobuf:"bytes,3,opt,name=roomName,proto3" json:"roomName,omitempty"`
	RoomDescription      string                     `protobuf:"bytes,4,opt,name=roomDescription,proto3" json:"roomDescription,omitempty"`
	RoomType             int32                      `protobuf:"varint,5,opt,name=roomType,proto3" json:"roomType,omitempty"`
	RoomPublicType       int32                      `protobuf:"varint,6,opt,name=roomPublicType,proto3" json:"roomPublicType,omitempty"`
	Max                  int32                      `protobuf:"varint,7,opt,name=max,proto3" json:"max,omitempty"`
	Current              int32                      `protobuf:"varint,8,opt,name=current,proto3" json:"current,omitempty"`
	PlayerMap            map[string]*RoomPlayerData `protobuf:"bytes,9,rep,name=playerMap,proto3" json:"playerMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{4}
}
func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomData) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RoomData) GetRoomDescription() string {
	if m != nil {
		return m.RoomDescription
	}
	return ""
}

func (m *RoomData) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *RoomData) GetRoomPublicType() int32 {
	if m != nil {
		return m.RoomPublicType
	}
	return 0
}

func (m *RoomData) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *RoomData) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *RoomData) GetPlayerMap() map[string]*RoomPlayerData {
	if m != nil {
		return m.PlayerMap
	}
	return nil
}

//角色详细的信息位置，朝向，模型信息
type RoomPlayerData struct {
	UserId               string            `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Avatar               string            `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Online               bool              `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	LastUpdate           int64             `protobuf:"varint,5,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	Position             *RoomPositionData `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	Direction            *Vector3Data      `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoomPlayerData) Reset()         { *m = RoomPlayerData{} }
func (m *RoomPlayerData) String() string { return proto.CompactTextString(m) }
func (*RoomPlayerData) ProtoMessage()    {}
func (*RoomPlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{5}
}
func (m *RoomPlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPlayerData.Unmarshal(m, b)
}
func (m *RoomPlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPlayerData.Marshal(b, m, deterministic)
}
func (m *RoomPlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPlayerData.Merge(m, src)
}
func (m *RoomPlayerData) XXX_Size() int {
	return xxx_messageInfo_RoomPlayerData.Size(m)
}
func (m *RoomPlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPlayerData proto.InternalMessageInfo

func (m *RoomPlayerData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RoomPlayerData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *RoomPlayerData) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *RoomPlayerData) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *RoomPlayerData) GetPosition() *RoomPositionData {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *RoomPlayerData) GetDirection() *Vector3Data {
	if m != nil {
		return m.Direction
	}
	return nil
}

//角色位置信息，local是相对坐标，暂时使用，global是wgs84坐标，后面要引入
type RoomPositionData struct {
	Local                *Vector3Data `protobuf:"bytes,2,opt,name=local,proto3" json:"local,omitempty"`
	Global               *Vector3Data `protobuf:"bytes,3,opt,name=global,proto3" json:"global,omitempty"`
	Coordinate           string       `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RoomPositionData) Reset()         { *m = RoomPositionData{} }
func (m *RoomPositionData) String() string { return proto.CompactTextString(m) }
func (*RoomPositionData) ProtoMessage()    {}
func (*RoomPositionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{6}
}
func (m *RoomPositionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPositionData.Unmarshal(m, b)
}
func (m *RoomPositionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPositionData.Marshal(b, m, deterministic)
}
func (m *RoomPositionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPositionData.Merge(m, src)
}
func (m *RoomPositionData) XXX_Size() int {
	return xxx_messageInfo_RoomPositionData.Size(m)
}
func (m *RoomPositionData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPositionData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPositionData proto.InternalMessageInfo

func (m *RoomPositionData) GetLocal() *Vector3Data {
	if m != nil {
		return m.Local
	}
	return nil
}

func (m *RoomPositionData) GetGlobal() *Vector3Data {
	if m != nil {
		return m.Global
	}
	return nil
}

func (m *RoomPositionData) GetCoordinate() string {
	if m != nil {
		return m.Coordinate
	}
	return ""
}

//坐标系三维坐标
type Vector3Data struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector3Data) Reset()         { *m = Vector3Data{} }
func (m *Vector3Data) String() string { return proto.CompactTextString(m) }
func (*Vector3Data) ProtoMessage()    {}
func (*Vector3Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{7}
}
func (m *Vector3Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector3Data.Unmarshal(m, b)
}
func (m *Vector3Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector3Data.Marshal(b, m, deterministic)
}
func (m *Vector3Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector3Data.Merge(m, src)
}
func (m *Vector3Data) XXX_Size() int {
	return xxx_messageInfo_Vector3Data.Size(m)
}
func (m *Vector3Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector3Data.DiscardUnknown(m)
}

var xxx_messageInfo_Vector3Data proto.InternalMessageInfo

func (m *Vector3Data) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector3Data) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector3Data) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

//列出当前有的房间
type ListRoomRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoomRequest) Reset()         { *m = ListRoomRequest{} }
func (m *ListRoomRequest) String() string { return proto.CompactTextString(m) }
func (*ListRoomRequest) ProtoMessage()    {}
func (*ListRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{8}
}
func (m *ListRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoomRequest.Unmarshal(m, b)
}
func (m *ListRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoomRequest.Marshal(b, m, deterministic)
}
func (m *ListRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoomRequest.Merge(m, src)
}
func (m *ListRoomRequest) XXX_Size() int {
	return xxx_messageInfo_ListRoomRequest.Size(m)
}
func (m *ListRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoomRequest proto.InternalMessageInfo

//端侧发送了ListRoom之后，服务器发送CurrentRoom信息
type CurrentRoomsData struct {
	RoomMap              map[string]*RoomData `protobuf:"bytes,2,rep,name=roomMap,proto3" json:"roomMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CurrentRoomsData) Reset()         { *m = CurrentRoomsData{} }
func (m *CurrentRoomsData) String() string { return proto.CompactTextString(m) }
func (*CurrentRoomsData) ProtoMessage()    {}
func (*CurrentRoomsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{9}
}
func (m *CurrentRoomsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentRoomsData.Unmarshal(m, b)
}
func (m *CurrentRoomsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentRoomsData.Marshal(b, m, deterministic)
}
func (m *CurrentRoomsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentRoomsData.Merge(m, src)
}
func (m *CurrentRoomsData) XXX_Size() int {
	return xxx_messageInfo_CurrentRoomsData.Size(m)
}
func (m *CurrentRoomsData) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentRoomsData.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentRoomsData proto.InternalMessageInfo

func (m *CurrentRoomsData) GetRoomMap() map[string]*RoomData {
	if m != nil {
		return m.RoomMap
	}
	return nil
}

//RM_CURRENT_ROOM_DATA
//用户选择一个加入的房间，以房间号为参数
type JoinRoomRequest struct {
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{10}
}
func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type SetPasswordRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordRequest) Reset()         { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()    {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{11}
}
func (m *SetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordRequest.Unmarshal(m, b)
}
func (m *SetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordRequest.Merge(m, src)
}
func (m *SetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetPasswordRequest.Size(m)
}
func (m *SetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordRequest proto.InternalMessageInfo

func (m *SetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SetRoomTypeRequest struct {
	RoomType             int32    `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRoomTypeRequest) Reset()         { *m = SetRoomTypeRequest{} }
func (m *SetRoomTypeRequest) String() string { return proto.CompactTextString(m) }
func (*SetRoomTypeRequest) ProtoMessage()    {}
func (*SetRoomTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{12}
}
func (m *SetRoomTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRoomTypeRequest.Unmarshal(m, b)
}
func (m *SetRoomTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRoomTypeRequest.Marshal(b, m, deterministic)
}
func (m *SetRoomTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRoomTypeRequest.Merge(m, src)
}
func (m *SetRoomTypeRequest) XXX_Size() int {
	return xxx_messageInfo_SetRoomTypeRequest.Size(m)
}
func (m *SetRoomTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRoomTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRoomTypeRequest proto.InternalMessageInfo

func (m *SetRoomTypeRequest) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

type SetRoomPublicTypeRequest struct {
	RoomPublicType       int32    `protobuf:"varint,1,opt,name=roomPublicType,proto3" json:"roomPublicType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRoomPublicTypeRequest) Reset()         { *m = SetRoomPublicTypeRequest{} }
func (m *SetRoomPublicTypeRequest) String() string { return proto.CompactTextString(m) }
func (*SetRoomPublicTypeRequest) ProtoMessage()    {}
func (*SetRoomPublicTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{13}
}
func (m *SetRoomPublicTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRoomPublicTypeRequest.Unmarshal(m, b)
}
func (m *SetRoomPublicTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRoomPublicTypeRequest.Marshal(b, m, deterministic)
}
func (m *SetRoomPublicTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRoomPublicTypeRequest.Merge(m, src)
}
func (m *SetRoomPublicTypeRequest) XXX_Size() int {
	return xxx_messageInfo_SetRoomPublicTypeRequest.Size(m)
}
func (m *SetRoomPublicTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRoomPublicTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRoomPublicTypeRequest proto.InternalMessageInfo

func (m *SetRoomPublicTypeRequest) GetRoomPublicType() int32 {
	if m != nil {
		return m.RoomPublicType
	}
	return 0
}

//一个用户邀请另一个用户，此时可能弹窗，提示房间信息和邀请人的信息
type InviteRoomCommand struct {
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomName             string   `protobuf:"bytes,3,opt,name=roomName,proto3" json:"roomName,omitempty"`
	InviterName          string   `protobuf:"bytes,4,opt,name=inviterName,proto3" json:"inviterName,omitempty"`
	InviterAccount       string   `protobuf:"bytes,5,opt,name=inviterAccount,proto3" json:"inviterAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRoomCommand) Reset()         { *m = InviteRoomCommand{} }
func (m *InviteRoomCommand) String() string { return proto.CompactTextString(m) }
func (*InviteRoomCommand) ProtoMessage()    {}
func (*InviteRoomCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{14}
}
func (m *InviteRoomCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRoomCommand.Unmarshal(m, b)
}
func (m *InviteRoomCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRoomCommand.Marshal(b, m, deterministic)
}
func (m *InviteRoomCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRoomCommand.Merge(m, src)
}
func (m *InviteRoomCommand) XXX_Size() int {
	return xxx_messageInfo_InviteRoomCommand.Size(m)
}
func (m *InviteRoomCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRoomCommand.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRoomCommand proto.InternalMessageInfo

func (m *InviteRoomCommand) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *InviteRoomCommand) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *InviteRoomCommand) GetInviterName() string {
	if m != nil {
		return m.InviterName
	}
	return ""
}

func (m *InviteRoomCommand) GetInviterAccount() string {
	if m != nil {
		return m.InviterAccount
	}
	return ""
}

type InviteRoomRequest struct {
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRoomRequest) Reset()         { *m = InviteRoomRequest{} }
func (m *InviteRoomRequest) String() string { return proto.CompactTextString(m) }
func (*InviteRoomRequest) ProtoMessage()    {}
func (*InviteRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{15}
}
func (m *InviteRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRoomRequest.Unmarshal(m, b)
}
func (m *InviteRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRoomRequest.Marshal(b, m, deterministic)
}
func (m *InviteRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRoomRequest.Merge(m, src)
}
func (m *InviteRoomRequest) XXX_Size() int {
	return xxx_messageInfo_InviteRoomRequest.Size(m)
}
func (m *InviteRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRoomRequest proto.InternalMessageInfo

func (m *InviteRoomRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type InviteRoomResponse struct {
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	RetCode              int32    `protobuf:"varint,3,opt,name=retCode,proto3" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRoomResponse) Reset()         { *m = InviteRoomResponse{} }
func (m *InviteRoomResponse) String() string { return proto.CompactTextString(m) }
func (*InviteRoomResponse) ProtoMessage()    {}
func (*InviteRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{16}
}
func (m *InviteRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRoomResponse.Unmarshal(m, b)
}
func (m *InviteRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRoomResponse.Marshal(b, m, deterministic)
}
func (m *InviteRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRoomResponse.Merge(m, src)
}
func (m *InviteRoomResponse) XXX_Size() int {
	return xxx_messageInfo_InviteRoomResponse.Size(m)
}
func (m *InviteRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRoomResponse proto.InternalMessageInfo

func (m *InviteRoomResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *InviteRoomResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

// 用户创建一个新的房间，给房间一个简单描述
type CreateRoomRequest struct {
	RoomName             string   `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	RoomDescription      string   `protobuf:"bytes,3,opt,name=roomDescription,proto3" json:"roomDescription,omitempty"`
	RoomType             int32    `protobuf:"varint,4,opt,name=roomType,proto3" json:"roomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{17}
}
func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

func (m *CreateRoomRequest) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *CreateRoomRequest) GetRoomDescription() string {
	if m != nil {
		return m.RoomDescription
	}
	return ""
}

func (m *CreateRoomRequest) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

//用户申请离开房间
type QuitRoomRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitRoomRequest) Reset()         { *m = QuitRoomRequest{} }
func (m *QuitRoomRequest) String() string { return proto.CompactTextString(m) }
func (*QuitRoomRequest) ProtoMessage()    {}
func (*QuitRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{18}
}
func (m *QuitRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitRoomRequest.Unmarshal(m, b)
}
func (m *QuitRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitRoomRequest.Marshal(b, m, deterministic)
}
func (m *QuitRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitRoomRequest.Merge(m, src)
}
func (m *QuitRoomRequest) XXX_Size() int {
	return xxx_messageInfo_QuitRoomRequest.Size(m)
}
func (m *QuitRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitRoomRequest proto.InternalMessageInfo

//quitroom的结果
type QuitRoomResponse struct {
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	RetCode              int32    `protobuf:"varint,3,opt,name=retCode,proto3" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitRoomResponse) Reset()         { *m = QuitRoomResponse{} }
func (m *QuitRoomResponse) String() string { return proto.CompactTextString(m) }
func (*QuitRoomResponse) ProtoMessage()    {}
func (*QuitRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{19}
}
func (m *QuitRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitRoomResponse.Unmarshal(m, b)
}
func (m *QuitRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitRoomResponse.Marshal(b, m, deterministic)
}
func (m *QuitRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitRoomResponse.Merge(m, src)
}
func (m *QuitRoomResponse) XXX_Size() int {
	return xxx_messageInfo_QuitRoomResponse.Size(m)
}
func (m *QuitRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitRoomResponse proto.InternalMessageInfo

func (m *QuitRoomResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *QuitRoomResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

//用户的同步的位移信息
type RoomMoveData struct {
	UserId               string            `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Position             *RoomPositionData `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Direction            *Vector3Data      `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	State                int32             `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoomMoveData) Reset()         { *m = RoomMoveData{} }
func (m *RoomMoveData) String() string { return proto.CompactTextString(m) }
func (*RoomMoveData) ProtoMessage()    {}
func (*RoomMoveData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{20}
}
func (m *RoomMoveData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMoveData.Unmarshal(m, b)
}
func (m *RoomMoveData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMoveData.Marshal(b, m, deterministic)
}
func (m *RoomMoveData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMoveData.Merge(m, src)
}
func (m *RoomMoveData) XXX_Size() int {
	return xxx_messageInfo_RoomMoveData.Size(m)
}
func (m *RoomMoveData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMoveData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMoveData proto.InternalMessageInfo

func (m *RoomMoveData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RoomMoveData) GetPosition() *RoomPositionData {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *RoomMoveData) GetDirection() *Vector3Data {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *RoomMoveData) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type NetMessage struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	Oid                  string   `protobuf:"bytes,3,opt,name=Oid,proto3" json:"Oid,omitempty"`
	Xid                  string   `protobuf:"bytes,4,opt,name=Xid,proto3" json:"Xid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetMessage) Reset()         { *m = NetMessage{} }
func (m *NetMessage) String() string { return proto.CompactTextString(m) }
func (*NetMessage) ProtoMessage()    {}
func (*NetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{21}
}
func (m *NetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetMessage.Unmarshal(m, b)
}
func (m *NetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetMessage.Marshal(b, m, deterministic)
}
func (m *NetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetMessage.Merge(m, src)
}
func (m *NetMessage) XXX_Size() int {
	return xxx_messageInfo_NetMessage.Size(m)
}
func (m *NetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NetMessage proto.InternalMessageInfo

func (m *NetMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NetMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *NetMessage) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *NetMessage) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

type RegServerRequest struct {
	ServerId             string   `protobuf:"bytes,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
	ServiceType          string   `protobuf:"bytes,3,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegServerRequest) Reset()         { *m = RegServerRequest{} }
func (m *RegServerRequest) String() string { return proto.CompactTextString(m) }
func (*RegServerRequest) ProtoMessage()    {}
func (*RegServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{22}
}
func (m *RegServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegServerRequest.Unmarshal(m, b)
}
func (m *RegServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegServerRequest.Marshal(b, m, deterministic)
}
func (m *RegServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegServerRequest.Merge(m, src)
}
func (m *RegServerRequest) XXX_Size() int {
	return xxx_messageInfo_RegServerRequest.Size(m)
}
func (m *RegServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegServerRequest proto.InternalMessageInfo

func (m *RegServerRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *RegServerRequest) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

type RegServerResponse struct {
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	RetCode              int32    `protobuf:"varint,3,opt,name=retCode,proto3" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegServerResponse) Reset()         { *m = RegServerResponse{} }
func (m *RegServerResponse) String() string { return proto.CompactTextString(m) }
func (*RegServerResponse) ProtoMessage()    {}
func (*RegServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{23}
}
func (m *RegServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegServerResponse.Unmarshal(m, b)
}
func (m *RegServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegServerResponse.Marshal(b, m, deterministic)
}
func (m *RegServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegServerResponse.Merge(m, src)
}
func (m *RegServerResponse) XXX_Size() int {
	return xxx_messageInfo_RegServerResponse.Size(m)
}
func (m *RegServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegServerResponse proto.InternalMessageInfo

func (m *RegServerResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *RegServerResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

type KeepaliveRequest struct {
	ServerId             string   `protobuf:"bytes,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
	ServiceType          string   `protobuf:"bytes,3,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepaliveRequest) Reset()         { *m = KeepaliveRequest{} }
func (m *KeepaliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepaliveRequest) ProtoMessage()    {}
func (*KeepaliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{24}
}
func (m *KeepaliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepaliveRequest.Unmarshal(m, b)
}
func (m *KeepaliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepaliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepaliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepaliveRequest.Merge(m, src)
}
func (m *KeepaliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepaliveRequest.Size(m)
}
func (m *KeepaliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepaliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepaliveRequest proto.InternalMessageInfo

func (m *KeepaliveRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *KeepaliveRequest) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

type KeepaliveResponse struct {
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	RetCode              int32    `protobuf:"varint,3,opt,name=retCode,proto3" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepaliveResponse) Reset()         { *m = KeepaliveResponse{} }
func (m *KeepaliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepaliveResponse) ProtoMessage()    {}
func (*KeepaliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{25}
}
func (m *KeepaliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepaliveResponse.Unmarshal(m, b)
}
func (m *KeepaliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepaliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepaliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepaliveResponse.Merge(m, src)
}
func (m *KeepaliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepaliveResponse.Size(m)
}
func (m *KeepaliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepaliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepaliveResponse proto.InternalMessageInfo

func (m *KeepaliveResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *KeepaliveResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

type LookData struct {
	UserId               string          `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Looks                map[int32]int32 `protobuf:"bytes,2,rep,name=looks,proto3" json:"looks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Timestamp            int64           `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LookData) Reset()         { *m = LookData{} }
func (m *LookData) String() string { return proto.CompactTextString(m) }
func (*LookData) ProtoMessage()    {}
func (*LookData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{26}
}
func (m *LookData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookData.Unmarshal(m, b)
}
func (m *LookData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookData.Marshal(b, m, deterministic)
}
func (m *LookData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookData.Merge(m, src)
}
func (m *LookData) XXX_Size() int {
	return xxx_messageInfo_LookData.Size(m)
}
func (m *LookData) XXX_DiscardUnknown() {
	xxx_messageInfo_LookData.DiscardUnknown(m)
}

var xxx_messageInfo_LookData proto.InternalMessageInfo

func (m *LookData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LookData) GetLooks() map[int32]int32 {
	if m != nil {
		return m.Looks
	}
	return nil
}

func (m *LookData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type LookRequest struct {
	Looks                map[int32]int32 `protobuf:"bytes,1,rep,name=looks,proto3" json:"looks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LookRequest) Reset()         { *m = LookRequest{} }
func (m *LookRequest) String() string { return proto.CompactTextString(m) }
func (*LookRequest) ProtoMessage()    {}
func (*LookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{27}
}
func (m *LookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookRequest.Unmarshal(m, b)
}
func (m *LookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookRequest.Marshal(b, m, deterministic)
}
func (m *LookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookRequest.Merge(m, src)
}
func (m *LookRequest) XXX_Size() int {
	return xxx_messageInfo_LookRequest.Size(m)
}
func (m *LookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookRequest proto.InternalMessageInfo

func (m *LookRequest) GetLooks() map[int32]int32 {
	if m != nil {
		return m.Looks
	}
	return nil
}

type PoseData struct {
	UserId               string            `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Poses                map[int32]float64 `protobuf:"bytes,2,rep,name=poses,proto3" json:"poses,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Timestamp            int64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PoseData) Reset()         { *m = PoseData{} }
func (m *PoseData) String() string { return proto.CompactTextString(m) }
func (*PoseData) ProtoMessage()    {}
func (*PoseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{28}
}
func (m *PoseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoseData.Unmarshal(m, b)
}
func (m *PoseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoseData.Marshal(b, m, deterministic)
}
func (m *PoseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoseData.Merge(m, src)
}
func (m *PoseData) XXX_Size() int {
	return xxx_messageInfo_PoseData.Size(m)
}
func (m *PoseData) XXX_DiscardUnknown() {
	xxx_messageInfo_PoseData.DiscardUnknown(m)
}

var xxx_messageInfo_PoseData proto.InternalMessageInfo

func (m *PoseData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PoseData) GetPoses() map[int32]float64 {
	if m != nil {
		return m.Poses
	}
	return nil
}

func (m *PoseData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PoseRequest struct {
	Poses                map[int32]float64 `protobuf:"bytes,1,rep,name=poses,proto3" json:"poses,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PoseRequest) Reset()         { *m = PoseRequest{} }
func (m *PoseRequest) String() string { return proto.CompactTextString(m) }
func (*PoseRequest) ProtoMessage()    {}
func (*PoseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{29}
}
func (m *PoseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoseRequest.Unmarshal(m, b)
}
func (m *PoseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoseRequest.Marshal(b, m, deterministic)
}
func (m *PoseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoseRequest.Merge(m, src)
}
func (m *PoseRequest) XXX_Size() int {
	return xxx_messageInfo_PoseRequest.Size(m)
}
func (m *PoseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PoseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PoseRequest proto.InternalMessageInfo

func (m *PoseRequest) GetPoses() map[int32]float64 {
	if m != nil {
		return m.Poses
	}
	return nil
}

type PackData struct {
	Poses                []*PoseData `protobuf:"bytes,1,rep,name=poses,proto3" json:"poses,omitempty"`
	Looks                []*LookData `protobuf:"bytes,2,rep,name=looks,proto3" json:"looks,omitempty"`
	Timestamp            int64       `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PackData) Reset()         { *m = PackData{} }
func (m *PackData) String() string { return proto.CompactTextString(m) }
func (*PackData) ProtoMessage()    {}
func (*PackData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{30}
}
func (m *PackData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackData.Unmarshal(m, b)
}
func (m *PackData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackData.Marshal(b, m, deterministic)
}
func (m *PackData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackData.Merge(m, src)
}
func (m *PackData) XXX_Size() int {
	return xxx_messageInfo_PackData.Size(m)
}
func (m *PackData) XXX_DiscardUnknown() {
	xxx_messageInfo_PackData.DiscardUnknown(m)
}

var xxx_messageInfo_PackData proto.InternalMessageInfo

func (m *PackData) GetPoses() []*PoseData {
	if m != nil {
		return m.Poses
	}
	return nil
}

func (m *PackData) GetLooks() []*LookData {
	if m != nil {
		return m.Looks
	}
	return nil
}

func (m *PackData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type KickRequest struct {
	Kicks                map[string]bool `protobuf:"bytes,1,rep,name=kicks,proto3" json:"kicks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *KickRequest) Reset()         { *m = KickRequest{} }
func (m *KickRequest) String() string { return proto.CompactTextString(m) }
func (*KickRequest) ProtoMessage()    {}
func (*KickRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{31}
}
func (m *KickRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickRequest.Unmarshal(m, b)
}
func (m *KickRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickRequest.Marshal(b, m, deterministic)
}
func (m *KickRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickRequest.Merge(m, src)
}
func (m *KickRequest) XXX_Size() int {
	return xxx_messageInfo_KickRequest.Size(m)
}
func (m *KickRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KickRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KickRequest proto.InternalMessageInfo

func (m *KickRequest) GetKicks() map[string]bool {
	if m != nil {
		return m.Kicks
	}
	return nil
}

type KickCommand struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickCommand) Reset()         { *m = KickCommand{} }
func (m *KickCommand) String() string { return proto.CompactTextString(m) }
func (*KickCommand) ProtoMessage()    {}
func (*KickCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{32}
}
func (m *KickCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickCommand.Unmarshal(m, b)
}
func (m *KickCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickCommand.Marshal(b, m, deterministic)
}
func (m *KickCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickCommand.Merge(m, src)
}
func (m *KickCommand) XXX_Size() int {
	return xxx_messageInfo_KickCommand.Size(m)
}
func (m *KickCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_KickCommand.DiscardUnknown(m)
}

var xxx_messageInfo_KickCommand proto.InternalMessageInfo

func (m *KickCommand) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *KickCommand) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type QuitCommand struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitCommand) Reset()         { *m = QuitCommand{} }
func (m *QuitCommand) String() string { return proto.CompactTextString(m) }
func (*QuitCommand) ProtoMessage()    {}
func (*QuitCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{33}
}
func (m *QuitCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitCommand.Unmarshal(m, b)
}
func (m *QuitCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitCommand.Marshal(b, m, deterministic)
}
func (m *QuitCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitCommand.Merge(m, src)
}
func (m *QuitCommand) XXX_Size() int {
	return xxx_messageInfo_QuitCommand.Size(m)
}
func (m *QuitCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitCommand.DiscardUnknown(m)
}

var xxx_messageInfo_QuitCommand proto.InternalMessageInfo

func (m *QuitCommand) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *QuitCommand) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterEnum("protoc.ROOM_MSG_TYPE", ROOM_MSG_TYPE_name, ROOM_MSG_TYPE_value)
	proto.RegisterType((*StandardResponse)(nil), "protoc.StandardResponse")
	proto.RegisterType((*StandardRequest)(nil), "protoc.StandardRequest")
	proto.RegisterType((*EnterRequest)(nil), "protoc.EnterRequest")
	proto.RegisterType((*EnterRoomCommand)(nil), "protoc.EnterRoomCommand")
	proto.RegisterType((*RoomData)(nil), "protoc.RoomData")
	proto.RegisterMapType((map[string]*RoomPlayerData)(nil), "protoc.RoomData.PlayerMapEntry")
	proto.RegisterType((*RoomPlayerData)(nil), "protoc.RoomPlayerData")
	proto.RegisterType((*RoomPositionData)(nil), "protoc.RoomPositionData")
	proto.RegisterType((*Vector3Data)(nil), "protoc.Vector3Data")
	proto.RegisterType((*ListRoomRequest)(nil), "protoc.ListRoomRequest")
	proto.RegisterType((*CurrentRoomsData)(nil), "protoc.CurrentRoomsData")
	proto.RegisterMapType((map[string]*RoomData)(nil), "protoc.CurrentRoomsData.RoomMapEntry")
	proto.RegisterType((*JoinRoomRequest)(nil), "protoc.JoinRoomRequest")
	proto.RegisterType((*SetPasswordRequest)(nil), "protoc.SetPasswordRequest")
	proto.RegisterType((*SetRoomTypeRequest)(nil), "protoc.SetRoomTypeRequest")
	proto.RegisterType((*SetRoomPublicTypeRequest)(nil), "protoc.SetRoomPublicTypeRequest")
	proto.RegisterType((*InviteRoomCommand)(nil), "protoc.InviteRoomCommand")
	proto.RegisterType((*InviteRoomRequest)(nil), "protoc.InviteRoomRequest")
	proto.RegisterType((*InviteRoomResponse)(nil), "protoc.InviteRoomResponse")
	proto.RegisterType((*CreateRoomRequest)(nil), "protoc.CreateRoomRequest")
	proto.RegisterType((*QuitRoomRequest)(nil), "protoc.QuitRoomRequest")
	proto.RegisterType((*QuitRoomResponse)(nil), "protoc.QuitRoomResponse")
	proto.RegisterType((*RoomMoveData)(nil), "protoc.RoomMoveData")
	proto.RegisterType((*NetMessage)(nil), "protoc.NetMessage")
	proto.RegisterType((*RegServerRequest)(nil), "protoc.RegServerRequest")
	proto.RegisterType((*RegServerResponse)(nil), "protoc.RegServerResponse")
	proto.RegisterType((*KeepaliveRequest)(nil), "protoc.KeepaliveRequest")
	proto.RegisterType((*KeepaliveResponse)(nil), "protoc.KeepaliveResponse")
	proto.RegisterType((*LookData)(nil), "protoc.LookData")
	proto.RegisterMapType((map[int32]int32)(nil), "protoc.LookData.LooksEntry")
	proto.RegisterType((*LookRequest)(nil), "protoc.LookRequest")
	proto.RegisterMapType((map[int32]int32)(nil), "protoc.LookRequest.LooksEntry")
	proto.RegisterType((*PoseData)(nil), "protoc.PoseData")
	proto.RegisterMapType((map[int32]float64)(nil), "protoc.PoseData.PosesEntry")
	proto.RegisterType((*PoseRequest)(nil), "protoc.PoseRequest")
	proto.RegisterMapType((map[int32]float64)(nil), "protoc.PoseRequest.PosesEntry")
	proto.RegisterType((*PackData)(nil), "protoc.PackData")
	proto.RegisterType((*KickRequest)(nil), "protoc.KickRequest")
	proto.RegisterMapType((map[string]bool)(nil), "protoc.KickRequest.KicksEntry")
	proto.RegisterType((*KickCommand)(nil), "protoc.KickCommand")
	proto.RegisterType((*QuitCommand)(nil), "protoc.QuitCommand")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 1639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4d, 0x6c, 0x1b, 0x4f,
	0x15, 0xef, 0xc6, 0x71, 0xbc, 0xfb, 0x9c, 0x26, 0xeb, 0x69, 0x1a, 0x5c, 0xb7, 0xb4, 0xd1, 0x8a,
	0x46, 0x29, 0x1f, 0xa1, 0x4d, 0x2b, 0x51, 0x90, 0x10, 0x72, 0xed, 0x2d, 0x72, 0xe3, 0xaf, 0x8c,
	0x9d, 0x40, 0x38, 0x60, 0x6d, 0xed, 0x21, 0xac, 0x62, 0x7b, 0xcd, 0xee, 0x3a, 0x24, 0x95, 0x90,
	0xe0, 0x82, 0x50, 0x4f, 0x45, 0xe2, 0xc4, 0x01, 0x09, 0x09, 0x10, 0x20, 0x81, 0x10, 0x27, 0x84,
	0xe0, 0x82, 0x90, 0x10, 0x12, 0x82, 0x1b, 0xe2, 0x08, 0xdc, 0x40, 0xf4, 0x82, 0x10, 0x27, 0x84,
	0xfe, 0x9a, 0xaf, 0xdd, 0xd9, 0xb5, 0xf3, 0x4f, 0x95, 0xfe, 0x4f, 0x9e, 0xf7, 0x39, 0xbf, 0xf7,
	0xe6, 0x37, 0x6f, 0x47, 0x06, 0xf0, 0x3d, 0x6f, 0xb4, 0x3d, 0xf1, 0xbd, 0xd0, 0x43, 0x4b, 0xec,
	0xa7, 0x6f, 0x55, 0xc1, 0xec, 0x84, 0xce, 0x78, 0xe0, 0xf8, 0x03, 0x4c, 0x82, 0x89, 0x37, 0x0e,
	0x08, 0x5a, 0x87, 0x25, 0xe2, 0xfb, 0x8d, 0xe0, 0xa8, 0xa8, 0x6d, 0x68, 0x5b, 0x06, 0x16, 0x12,
	0x2a, 0x42, 0xce, 0x27, 0x61, 0xc5, 0x1b, 0x90, 0xe2, 0xc2, 0x86, 0xb6, 0x95, 0xc5, 0x52, 0xb4,
	0x0a, 0xb0, 0x1a, 0x67, 0xf9, 0xd2, 0x94, 0x04, 0xa1, 0xb5, 0x02, 0xcb, 0xf6, 0x38, 0x24, 0xbe,
	0x94, 0x7f, 0xac, 0x81, 0xc9, 0x15, 0x9e, 0x37, 0xaa, 0x78, 0xa3, 0x91, 0x33, 0x1e, 0xa0, 0x12,
	0xe8, 0x14, 0x53, 0xf7, 0x6c, 0xc2, 0x53, 0x1a, 0x38, 0x92, 0x29, 0x0a, 0xba, 0xae, 0x0d, 0x8a,
	0x19, 0x8e, 0x82, 0x4b, 0xe8, 0x16, 0x18, 0x74, 0x85, 0x49, 0x50, 0x1b, 0x14, 0x17, 0x99, 0x29,
	0x56, 0xc8, 0x8c, 0x4d, 0x67, 0x44, 0x8a, 0xd9, 0x38, 0x23, 0x95, 0xd1, 0x16, 0xac, 0xd2, 0x75,
	0x95, 0x04, 0x7d, 0xdf, 0x9d, 0x84, 0xae, 0x37, 0x2e, 0x2e, 0x31, 0x97, 0xb4, 0xda, 0x7a, 0xbd,
	0x00, 0x3a, 0xc5, 0x59, 0x75, 0x42, 0x47, 0x01, 0xb2, 0x90, 0x00, 0xa2, 0x6e, 0x95, 0xb9, 0x78,
	0xab, 0xc5, 0xb9, 0x5b, 0x25, 0x5a, 0x90, 0x65, 0x5d, 0x8d, 0x5b, 0xb0, 0x09, 0x2b, 0x74, 0xdd,
	0x9e, 0x3e, 0x1f, 0xba, 0x7d, 0xe6, 0xb1, 0xc4, 0x3c, 0x52, 0x5a, 0x64, 0x42, 0x66, 0xe4, 0x9c,
	0x16, 0x73, 0xcc, 0x48, 0x97, 0xf4, 0xa8, 0xfa, 0x53, 0xdf, 0x27, 0xe3, 0xb0, 0xa8, 0xf3, 0xa3,
	0x12, 0x22, 0xfa, 0x24, 0x18, 0x93, 0xa1, 0x73, 0x46, 0xfc, 0x86, 0x33, 0x29, 0x1a, 0x1b, 0x99,
	0xad, 0xfc, 0xce, 0x1d, 0xce, 0x89, 0xfe, 0xb6, 0x2c, 0x79, 0xbb, 0x2d, 0x3d, 0xec, 0x71, 0xe8,
	0x9f, 0xe1, 0x38, 0xa2, 0xd4, 0x85, 0x95, 0xa4, 0x91, 0x6e, 0x7e, 0x4c, 0xce, 0x04, 0x55, 0xe8,
	0x12, 0x7d, 0x18, 0xb2, 0x27, 0xce, 0x70, 0xca, 0x8f, 0x34, 0xbf, 0xb3, 0xae, 0xa6, 0xe7, 0xc1,
	0x74, 0x13, 0xcc, 0x9d, 0x3e, 0xb1, 0xf0, 0x58, 0xb3, 0xfe, 0xa6, 0xc1, 0x4a, 0xd2, 0x4a, 0xbb,
	0x3e, 0x0d, 0x88, 0x1f, 0x77, 0x9d, 0x4b, 0x54, 0xef, 0x9c, 0x38, 0xa1, 0xe3, 0x4b, 0x5a, 0x70,
	0x89, 0xea, 0xbd, 0xf1, 0xd0, 0x1d, 0x13, 0xd6, 0x68, 0x1d, 0x0b, 0x09, 0xdd, 0x06, 0x18, 0x3a,
	0x41, 0xb8, 0x3f, 0x19, 0x38, 0x21, 0xef, 0x70, 0x06, 0x2b, 0x1a, 0xf4, 0x08, 0xf4, 0x89, 0x17,
	0xb8, 0x11, 0x1b, 0xf2, 0x3b, 0xc5, 0x04, 0x5e, 0x61, 0x63, 0x88, 0x23, 0x4f, 0xf4, 0x00, 0x8c,
	0x81, 0xeb, 0x93, 0x3e, 0x0b, 0xcb, 0xb1, 0xb0, 0x6b, 0x32, 0xec, 0x80, 0xf4, 0x43, 0xcf, 0x7f,
	0xc8, 0x22, 0x62, 0x2f, 0xeb, 0xa5, 0x06, 0x66, 0x3a, 0x23, 0xba, 0x07, 0xd9, 0xa1, 0xd7, 0x77,
	0x86, 0xa2, 0x55, 0x73, 0x73, 0x70, 0x0f, 0xf4, 0x21, 0x58, 0x3a, 0x1a, 0x7a, 0xcf, 0x9d, 0x21,
	0x2b, 0xfc, 0x1c, 0x5f, 0xe1, 0x42, 0xab, 0xee, 0x7b, 0x9e, 0x3f, 0x70, 0xc7, 0xb4, 0x6a, 0x4e,
	0x3d, 0x45, 0x63, 0x7d, 0x0c, 0xf2, 0x4a, 0x18, 0x5a, 0x06, 0xed, 0x94, 0x9d, 0xa0, 0x86, 0xb5,
	0x53, 0x2a, 0x9d, 0x31, 0x40, 0x1a, 0xd6, 0xce, 0xa8, 0xf4, 0x82, 0x6d, 0xa9, 0x61, 0xed, 0x05,
	0xbd, 0xe9, 0x75, 0x37, 0x08, 0x31, 0xbb, 0x70, 0xfc, 0x66, 0x7f, 0x57, 0x03, 0xb3, 0xc2, 0xd9,
	0x45, 0xd5, 0x01, 0xcb, 0xf8, 0x29, 0xc8, 0x51, 0x92, 0x52, 0x92, 0x2d, 0x30, 0x92, 0xdd, 0x95,
	0x70, 0xd3, 0xae, 0xac, 0xcd, 0x11, 0xd5, 0x64, 0x54, 0xa9, 0x0e, 0xcb, 0xaa, 0x61, 0x0e, 0xcd,
	0x36, 0x93, 0x34, 0x33, 0xd3, 0x2c, 0x56, 0x09, 0x76, 0x0f, 0x56, 0x9f, 0x79, 0xee, 0x58, 0x81,
	0x7d, 0xde, 0xb5, 0xb6, 0xee, 0x03, 0xea, 0x90, 0xb0, 0xed, 0x04, 0xc1, 0x97, 0xbd, 0x68, 0x9c,
	0xd1, 0x6b, 0x3a, 0x11, 0x2a, 0x81, 0x21, 0x92, 0x45, 0x04, 0x16, 0xb7, 0x56, 0x89, 0x88, 0x2e,
	0xb6, 0x96, 0xbc, 0xd8, 0xd6, 0x13, 0x28, 0x8a, 0x88, 0xf8, 0x16, 0xcb, 0xb8, 0xd9, 0x4b, 0xaf,
	0xcd, 0xbb, 0xf4, 0xd6, 0x37, 0x35, 0x28, 0xd4, 0xc6, 0x27, 0x6e, 0x48, 0xd4, 0x89, 0x7a, 0x99,
	0x61, 0xb5, 0x01, 0x79, 0x97, 0x25, 0xf2, 0x99, 0x99, 0xb3, 0x45, 0x55, 0x51, 0x4c, 0x42, 0x2c,
	0xf7, 0xfb, 0xde, 0x74, 0x1c, 0x8a, 0xd9, 0x9a, 0xd2, 0x5a, 0x1f, 0x51, 0x21, 0xc9, 0x82, 0x8a,
	0x90, 0x73, 0x44, 0x14, 0xc7, 0x24, 0x45, 0xeb, 0x29, 0x20, 0xd5, 0x7d, 0xe6, 0xf3, 0xb3, 0x70,
	0xde, 0xe7, 0x27, 0x93, 0xfc, 0xfc, 0x4c, 0xa1, 0x50, 0xf1, 0x89, 0x93, 0xdc, 0x56, 0xad, 0x78,
	0xe1, 0xe2, 0xf1, 0x9c, 0xb9, 0x78, 0x3c, 0x2f, 0xa6, 0x4e, 0xb1, 0x00, 0xab, 0x7b, 0x53, 0x37,
	0x71, 0x17, 0xaa, 0x60, 0xc6, 0xaa, 0x4b, 0xd7, 0xf3, 0x7d, 0x4d, 0x90, 0xdf, 0x3b, 0x21, 0xef,
	0x3a, 0x0c, 0xd5, 0xe1, 0x95, 0xb9, 0xdc, 0xf0, 0x5a, 0x7c, 0x93, 0xe1, 0x85, 0xd6, 0x20, 0x1b,
	0x84, 0x72, 0x80, 0x66, 0x31, 0x17, 0xac, 0xcf, 0x03, 0x34, 0x49, 0xd8, 0x20, 0x41, 0xe0, 0x1c,
	0x11, 0x84, 0x60, 0x51, 0xa1, 0x2b, 0x5b, 0xd3, 0x1a, 0x2b, 0xde, 0x38, 0x24, 0xe2, 0xec, 0x97,
	0xb1, 0x14, 0xe9, 0x7d, 0x6e, 0xb9, 0xf2, 0xdb, 0x4e, 0x97, 0x54, 0xf3, 0x59, 0x57, 0x7e, 0xd2,
	0xe9, 0xd2, 0x6a, 0x83, 0x89, 0xc9, 0x51, 0x87, 0xf8, 0x27, 0xd1, 0x3b, 0x82, 0x1e, 0x48, 0xc0,
	0x14, 0x51, 0x33, 0x22, 0x99, 0x12, 0x99, 0xae, 0xdd, 0x3e, 0x61, 0x40, 0x78, 0x6e, 0x55, 0x65,
	0xd9, 0x50, 0x50, 0x32, 0x5e, 0xfa, 0x80, 0xda, 0x60, 0xee, 0x12, 0x32, 0x71, 0x86, 0xee, 0x09,
	0x79, 0xcf, 0x80, 0x29, 0x19, 0x2f, 0x0d, 0xec, 0x27, 0x1a, 0xe8, 0x75, 0xcf, 0x3b, 0x4e, 0xb1,
	0x46, 0x4b, 0xb0, 0xe6, 0x01, 0xfd, 0xe8, 0x78, 0xc7, 0x81, 0x98, 0xcc, 0x37, 0xe5, 0xd9, 0xcb,
	0x40, 0xb6, 0x08, 0xf8, 0x3c, 0xe6, 0x9e, 0xf4, 0xd1, 0x15, 0xba, 0x23, 0x12, 0x84, 0xce, 0x68,
	0xc2, 0xf6, 0xcc, 0xe0, 0x58, 0x51, 0x7a, 0x0c, 0x10, 0x87, 0xa8, 0x93, 0x3a, 0xcb, 0x27, 0xf5,
	0x9a, 0x3a, 0xa9, 0xb3, 0xea, 0x5c, 0xfe, 0x0a, 0xe4, 0x69, 0xa4, 0xec, 0xe1, 0x23, 0x89, 0x4c,
	0x63, 0xc8, 0x6e, 0xab, 0xc8, 0x84, 0xcf, 0x2c, 0xb8, 0xb7, 0xd8, 0x9e, 0xb6, 0xab, 0xed, 0x05,
	0xe4, 0xa2, 0x76, 0x4d, 0xbc, 0x80, 0xcc, 0xb4, 0x4b, 0x06, 0xb2, 0x85, 0x44, 0xc4, 0x3c, 0x2f,
	0x6e, 0x57, 0x1c, 0x72, 0x11, 0x5e, 0x2d, 0xd5, 0x2e, 0x1a, 0xa9, 0xb4, 0x8b, 0x23, 0x4b, 0xb5,
	0x4b, 0xf1, 0x99, 0x05, 0xf7, 0x16, 0xdb, 0x9f, 0x82, 0xde, 0x76, 0xfa, 0x9c, 0x5c, 0x9b, 0xc9,
	0xbd, 0xcd, 0x74, 0x57, 0x64, 0x2b, 0x36, 0x93, 0x64, 0x33, 0xd3, 0x64, 0x7b, 0x23, 0x86, 0xd1,
	0xc2, 0x77, 0xdd, 0xbe, 0xca, 0x93, 0x63, 0xb7, 0x3f, 0xcb, 0x13, 0xc5, 0x87, 0xad, 0x65, 0xe1,
	0xcc, 0x99, 0x16, 0x1e, 0x2b, 0xe7, 0x3c, 0x28, 0x12, 0x85, 0xeb, 0x6a, 0xe1, 0x65, 0xbe, 0xbd,
	0xf2, 0x91, 0x9d, 0xcb, 0x94, 0x12, 0xe8, 0x74, 0xa5, 0x7e, 0x72, 0xa4, 0x4c, 0x53, 0xd0, 0x2f,
	0xc3, 0x5b, 0xa4, 0xf8, 0xe0, 0x9f, 0x74, 0xb8, 0x8a, 0x5b, 0xad, 0x46, 0xaf, 0xd1, 0xf9, 0x74,
	0xaf, 0x7b, 0xd8, 0xb6, 0xd1, 0x0a, 0x00, 0x6e, 0xf4, 0xaa, 0xf6, 0xd3, 0xf2, 0x7e, 0xbd, 0x6b,
	0x5e, 0x41, 0x05, 0xb8, 0x8a, 0x1b, 0xbd, 0x5d, 0xdb, 0x6e, 0xf7, 0xca, 0xf5, 0xda, 0x81, 0x6d,
	0x6a, 0xe8, 0x3a, 0x98, 0xb8, 0xd1, 0xb3, 0x9b, 0x5d, 0x1b, 0xf7, 0xb0, 0xbd, 0xb7, 0x6f, 0x77,
	0xba, 0xe6, 0x3f, 0x72, 0x68, 0x1d, 0x0a, 0x8a, 0xba, 0xd3, 0x6e, 0x35, 0x3b, 0xb6, 0xf9, 0x3a,
	0x87, 0x4a, 0x70, 0x3d, 0xd6, 0xd3, 0xbd, 0x2a, 0xad, 0x46, 0xa3, 0xdc, 0xac, 0x9a, 0xff, 0x96,
	0xb6, 0xbd, 0x7d, 0x1b, 0x1f, 0x72, 0x9b, 0xcc, 0xf7, 0xbf, 0x1c, 0xba, 0x09, 0xeb, 0x69, 0x9b,
	0x48, 0xfa, 0x35, 0x1d, 0x15, 0x60, 0x19, 0x37, 0xb8, 0xba, 0x5a, 0xee, 0x96, 0xcd, 0xaf, 0xeb,
	0xa8, 0x08, 0xd7, 0xa4, 0xaa, 0x5d, 0x2f, 0x1f, 0xda, 0x98, 0x5b, 0x5e, 0xe9, 0x62, 0x17, 0x6e,
	0x69, 0x75, 0x6a, 0xdd, 0x5a, 0xab, 0xc9, 0x6d, 0xdf, 0xd6, 0xd1, 0x0d, 0x58, 0xc3, 0x8d, 0x5e,
	0xbd, 0xd6, 0xe9, 0x26, 0x01, 0x7c, 0x4f, 0x86, 0xa9, 0x26, 0xb1, 0xff, 0x8f, 0x64, 0x58, 0x65,
	0x1f, 0x63, 0xbb, 0xd9, 0x55, 0x70, 0xfc, 0x54, 0x9a, 0x9e, 0xb5, 0x6a, 0xcd, 0x64, 0xc6, 0x5f,
	0xc8, 0x8c, 0xaa, 0x49, 0x64, 0xfc, 0xb5, 0x2e, 0xca, 0xad, 0x35, 0x0f, 0x6a, 0x5d, 0x3b, 0xd9,
	0xa7, 0xdf, 0xcc, 0x33, 0xca, 0xac, 0xbf, 0xd3, 0xd1, 0x2d, 0x78, 0xdf, 0x8c, 0x51, 0xe4, 0xfd,
	0xbd, 0x0c, 0xad, 0x60, 0xbb, 0x9c, 0x0e, 0xfd, 0x83, 0x0c, 0x4d, 0x1a, 0x45, 0xe8, 0x9f, 0x65,
	0x25, 0x7b, 0xfb, 0xb5, 0x54, 0x6f, 0xfe, 0xaa, 0x47, 0x07, 0x57, 0x4b, 0xf7, 0xe6, 0x9f, 0xba,
	0x20, 0x02, 0xa7, 0x55, 0xeb, 0xc0, 0xe6, 0x8d, 0xf9, 0x4f, 0xd4, 0xcf, 0x56, 0xb9, 0xda, 0xc3,
	0x76, 0xb9, 0x7a, 0x18, 0xe5, 0xfb, 0xbf, 0x44, 0x99, 0xb0, 0x89, 0x84, 0xdf, 0x30, 0x04, 0x0e,
	0xca, 0x41, 0x46, 0xc1, 0x28, 0xee, 0x07, 0x86, 0xc8, 0xa9, 0x9a, 0x44, 0xd8, 0xcf, 0x0c, 0xb4,
	0x06, 0xab, 0x2c, 0x67, 0x6b, 0x37, 0x8a, 0xf8, 0xa5, 0x21, 0xd8, 0x2b, 0xb4, 0xc2, 0xf9, 0xb7,
	0x86, 0x20, 0x14, 0x53, 0x33, 0xbc, 0x7f, 0x34, 0x44, 0x73, 0x3a, 0x76, 0xb7, 0xd7, 0x2e, 0x77,
	0x3a, 0x9f, 0x69, 0xe1, 0x6a, 0x94, 0xe7, 0x2f, 0x06, 0x7a, 0x3f, 0x14, 0x67, 0xad, 0x22, 0xdf,
	0xdf, 0x55, 0x33, 0x6b, 0x04, 0xbd, 0x5b, 0x51, 0xf4, 0xbf, 0x0c, 0x74, 0x1b, 0x6e, 0xcc, 0x31,
	0x8b, 0xf0, 0xff, 0x4a, 0x38, 0xed, 0x72, 0x45, 0xc0, 0xf9, 0x2a, 0x88, 0x72, 0x76, 0x6b, 0x95,
	0xb8, 0x9c, 0x97, 0x20, 0xca, 0x11, 0x5a, 0x11, 0xff, 0xad, 0x84, 0xb3, 0xa4, 0xd1, 0x77, 0xa4,
	0x96, 0x9d, 0x9a, 0xd4, 0xfe, 0x10, 0xd0, 0x07, 0xe0, 0x8e, 0x8a, 0xa5, 0xbd, 0xff, 0xa4, 0x5e,
	0xab, 0x24, 0x11, 0xff, 0x1c, 0xd0, 0x5d, 0xd8, 0x38, 0xdf, 0x4b, 0x6c, 0xfc, 0x2b, 0xd8, 0x79,
	0xa5, 0x41, 0x9e, 0x3e, 0x14, 0x3b, 0xfc, 0x25, 0x82, 0x9e, 0xc2, 0x55, 0x4c, 0xbe, 0xe0, 0x93,
	0xe0, 0x8b, 0xfc, 0x89, 0x84, 0xe2, 0xe7, 0x64, 0xea, 0x1d, 0x56, 0xba, 0x31, 0xc7, 0xc2, 0x9f,
	0x2d, 0xd6, 0x15, 0xf4, 0x71, 0x30, 0x1a, 0xc1, 0x51, 0x27, 0xf4, 0x89, 0x33, 0x42, 0x48, 0x7a,
	0xc6, 0x6f, 0xc5, 0xd2, 0x1c, 0x9d, 0x75, 0x65, 0x4b, 0xbb, 0xaf, 0x3d, 0xc9, 0x7f, 0xce, 0xd8,
	0xde, 0xfe, 0x28, 0xb7, 0x3e, 0xe7, 0xff, 0x52, 0x3d, 0x7c, 0x27, 0x00, 0x00, 0xff, 0xff, 0xfb,
	0xda, 0x7c, 0x27, 0xba, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomServiceClient interface {
	RefreshServer(ctx context.Context, in *RegServerRequest, opts ...grpc.CallOption) (*RegServerResponse, error)
	MsgStream(ctx context.Context, opts ...grpc.CallOption) (RoomService_MsgStreamClient, error)
}

type roomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomServiceClient(cc *grpc.ClientConn) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) RefreshServer(ctx context.Context, in *RegServerRequest, opts ...grpc.CallOption) (*RegServerResponse, error) {
	out := new(RegServerResponse)
	err := c.cc.Invoke(ctx, "/protoc.RoomService/RefreshServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) MsgStream(ctx context.Context, opts ...grpc.CallOption) (RoomService_MsgStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RoomService_serviceDesc.Streams[0], "/protoc.RoomService/MsgStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &roomServiceMsgStreamClient{stream}
	return x, nil
}

type RoomService_MsgStreamClient interface {
	Send(*NetMessage) error
	Recv() (*NetMessage, error)
	grpc.ClientStream
}

type roomServiceMsgStreamClient struct {
	grpc.ClientStream
}

func (x *roomServiceMsgStreamClient) Send(m *NetMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *roomServiceMsgStreamClient) Recv() (*NetMessage, error) {
	m := new(NetMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoomServiceServer is the server API for RoomService service.
type RoomServiceServer interface {
	RefreshServer(context.Context, *RegServerRequest) (*RegServerResponse, error)
	MsgStream(RoomService_MsgStreamServer) error
}

// UnimplementedRoomServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoomServiceServer struct {
}

func (*UnimplementedRoomServiceServer) RefreshServer(ctx context.Context, req *RegServerRequest) (*RegServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshServer not implemented")
}
func (*UnimplementedRoomServiceServer) MsgStream(srv RoomService_MsgStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method MsgStream not implemented")
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_RefreshServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).RefreshServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.RoomService/RefreshServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).RefreshServer(ctx, req.(*RegServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_MsgStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoomServiceServer).MsgStream(&roomServiceMsgStreamServer{stream})
}

type RoomService_MsgStreamServer interface {
	Send(*NetMessage) error
	Recv() (*NetMessage, error)
	grpc.ServerStream
}

type roomServiceMsgStreamServer struct {
	grpc.ServerStream
}

func (x *roomServiceMsgStreamServer) Send(m *NetMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *roomServiceMsgStreamServer) Recv() (*NetMessage, error) {
	m := new(NetMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshServer",
			Handler:    _RoomService_RefreshServer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MsgStream",
			Handler:       _RoomService_MsgStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "room.proto",
}
