// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: room_status.proto

package protoc

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ROOM_STATUS_MSG_TYPE int32

const (
	ROOM_STATUS_MSG_TYPE_RSM_DEFAULT                ROOM_STATUS_MSG_TYPE = 0
	ROOM_STATUS_MSG_TYPE_RSM_CURRENT_USERS_REQUEST  ROOM_STATUS_MSG_TYPE = 3001
	ROOM_STATUS_MSG_TYPE_RSM_CURRENT_USERS_RESPONSE ROOM_STATUS_MSG_TYPE = 3005
	ROOM_STATUS_MSG_TYPE_RSM_USER_DATA              ROOM_STATUS_MSG_TYPE = 3010
	ROOM_STATUS_MSG_TYPE_RSM_CURRENT_USERS_DATA     ROOM_STATUS_MSG_TYPE = 3020
	ROOM_STATUS_MSG_TYPE_RSM_CLOSE_MIC_REQUEST      ROOM_STATUS_MSG_TYPE = 3030
	ROOM_STATUS_MSG_TYPE_RSM_CLOSE_MIC_RESPONSE     ROOM_STATUS_MSG_TYPE = 3040
	ROOM_STATUS_MSG_TYPE_RSM_CLOSE_MIC_COMMAND      ROOM_STATUS_MSG_TYPE = 3045
	ROOM_STATUS_MSG_TYPE_RSM_OPEN_MIC_REQUEST       ROOM_STATUS_MSG_TYPE = 3050
	ROOM_STATUS_MSG_TYPE_RSM_OPEN_MIC_RESPONSE      ROOM_STATUS_MSG_TYPE = 3060
	ROOM_STATUS_MSG_TYPE_RSM_OPEN_MIC_COMMAND       ROOM_STATUS_MSG_TYPE = 3065
	ROOM_STATUS_MSG_TYPE_RSM_SKILL_ACTION_REQUEST   ROOM_STATUS_MSG_TYPE = 3070
	ROOM_STATUS_MSG_TYPE_RSM_SKILL_ACTION_RESPONSE  ROOM_STATUS_MSG_TYPE = 3080
	ROOM_STATUS_MSG_TYPE_RSM_SKILL_ACTION_COMMAND   ROOM_STATUS_MSG_TYPE = 3090
)

var ROOM_STATUS_MSG_TYPE_name = map[int32]string{
	0:    "RSM_DEFAULT",
	3001: "RSM_CURRENT_USERS_REQUEST",
	3005: "RSM_CURRENT_USERS_RESPONSE",
	3010: "RSM_USER_DATA",
	3020: "RSM_CURRENT_USERS_DATA",
	3030: "RSM_CLOSE_MIC_REQUEST",
	3040: "RSM_CLOSE_MIC_RESPONSE",
	3045: "RSM_CLOSE_MIC_COMMAND",
	3050: "RSM_OPEN_MIC_REQUEST",
	3060: "RSM_OPEN_MIC_RESPONSE",
	3065: "RSM_OPEN_MIC_COMMAND",
	3070: "RSM_SKILL_ACTION_REQUEST",
	3080: "RSM_SKILL_ACTION_RESPONSE",
	3090: "RSM_SKILL_ACTION_COMMAND",
}

var ROOM_STATUS_MSG_TYPE_value = map[string]int32{
	"RSM_DEFAULT":                0,
	"RSM_CURRENT_USERS_REQUEST":  3001,
	"RSM_CURRENT_USERS_RESPONSE": 3005,
	"RSM_USER_DATA":              3010,
	"RSM_CURRENT_USERS_DATA":     3020,
	"RSM_CLOSE_MIC_REQUEST":      3030,
	"RSM_CLOSE_MIC_RESPONSE":     3040,
	"RSM_CLOSE_MIC_COMMAND":      3045,
	"RSM_OPEN_MIC_REQUEST":       3050,
	"RSM_OPEN_MIC_RESPONSE":      3060,
	"RSM_OPEN_MIC_COMMAND":       3065,
	"RSM_SKILL_ACTION_REQUEST":   3070,
	"RSM_SKILL_ACTION_RESPONSE":  3080,
	"RSM_SKILL_ACTION_COMMAND":   3090,
}

func (x ROOM_STATUS_MSG_TYPE) String() string {
	return proto.EnumName(ROOM_STATUS_MSG_TYPE_name, int32(x))
}

func (ROOM_STATUS_MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f6a5f28d4a278e7, []int{0}
}

type UserData struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp            int32    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Followed             bool     `protobuf:"varint,4,opt,name=followed,proto3" json:"followed,omitempty"`
	Mic                  bool     `protobuf:"varint,5,opt,name=mic,proto3" json:"mic,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Leader               bool     `protobuf:"varint,7,opt,name=leader,proto3" json:"leader,omitempty"`
	Self                 bool     `protobuf:"varint,8,opt,name=self,proto3" json:"self,omitempty"`
	Online               bool     `protobuf:"varint,9,opt,name=online,proto3" json:"online,omitempty"`
	OffLineTime          int32    `protobuf:"varint,10,opt,name=offLineTime,proto3" json:"offLineTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6a5f28d4a278e7, []int{0}
}
func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserData) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UserData) GetFollowed() bool {
	if m != nil {
		return m.Followed
	}
	return false
}

func (m *UserData) GetMic() bool {
	if m != nil {
		return m.Mic
	}
	return false
}

func (m *UserData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserData) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

func (m *UserData) GetSelf() bool {
	if m != nil {
		return m.Self
	}
	return false
}

func (m *UserData) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *UserData) GetOffLineTime() int32 {
	if m != nil {
		return m.OffLineTime
	}
	return 0
}

type CurrentUsersData struct {
	Users                []*UserData `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Max                  int32       `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Now                  int32       `protobuf:"varint,3,opt,name=now,proto3" json:"now,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CurrentUsersData) Reset()         { *m = CurrentUsersData{} }
func (m *CurrentUsersData) String() string { return proto.CompactTextString(m) }
func (*CurrentUsersData) ProtoMessage()    {}
func (*CurrentUsersData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6a5f28d4a278e7, []int{1}
}
func (m *CurrentUsersData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentUsersData.Unmarshal(m, b)
}
func (m *CurrentUsersData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentUsersData.Marshal(b, m, deterministic)
}
func (m *CurrentUsersData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentUsersData.Merge(m, src)
}
func (m *CurrentUsersData) XXX_Size() int {
	return xxx_messageInfo_CurrentUsersData.Size(m)
}
func (m *CurrentUsersData) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentUsersData.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentUsersData proto.InternalMessageInfo

func (m *CurrentUsersData) GetUsers() []*UserData {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *CurrentUsersData) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *CurrentUsersData) GetNow() int32 {
	if m != nil {
		return m.Now
	}
	return 0
}

type CloseMicRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseMicRequest) Reset()         { *m = CloseMicRequest{} }
func (m *CloseMicRequest) String() string { return proto.CompactTextString(m) }
func (*CloseMicRequest) ProtoMessage()    {}
func (*CloseMicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6a5f28d4a278e7, []int{2}
}
func (m *CloseMicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseMicRequest.Unmarshal(m, b)
}
func (m *CloseMicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseMicRequest.Marshal(b, m, deterministic)
}
func (m *CloseMicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseMicRequest.Merge(m, src)
}
func (m *CloseMicRequest) XXX_Size() int {
	return xxx_messageInfo_CloseMicRequest.Size(m)
}
func (m *CloseMicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseMicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseMicRequest proto.InternalMessageInfo

func (m *CloseMicRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type OpenMicRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenMicRequest) Reset()         { *m = OpenMicRequest{} }
func (m *OpenMicRequest) String() string { return proto.CompactTextString(m) }
func (*OpenMicRequest) ProtoMessage()    {}
func (*OpenMicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6a5f28d4a278e7, []int{3}
}
func (m *OpenMicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenMicRequest.Unmarshal(m, b)
}
func (m *OpenMicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenMicRequest.Marshal(b, m, deterministic)
}
func (m *OpenMicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenMicRequest.Merge(m, src)
}
func (m *OpenMicRequest) XXX_Size() int {
	return xxx_messageInfo_OpenMicRequest.Size(m)
}
func (m *OpenMicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenMicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenMicRequest proto.InternalMessageInfo

func (m *OpenMicRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SkillActionRequest struct {
	Action               int32        `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	Direction            *Vector3Data `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	TargetId             string       `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SkillActionRequest) Reset()         { *m = SkillActionRequest{} }
func (m *SkillActionRequest) String() string { return proto.CompactTextString(m) }
func (*SkillActionRequest) ProtoMessage()    {}
func (*SkillActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6a5f28d4a278e7, []int{4}
}
func (m *SkillActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillActionRequest.Unmarshal(m, b)
}
func (m *SkillActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillActionRequest.Marshal(b, m, deterministic)
}
func (m *SkillActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillActionRequest.Merge(m, src)
}
func (m *SkillActionRequest) XXX_Size() int {
	return xxx_messageInfo_SkillActionRequest.Size(m)
}
func (m *SkillActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SkillActionRequest proto.InternalMessageInfo

func (m *SkillActionRequest) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *SkillActionRequest) GetDirection() *Vector3Data {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *SkillActionRequest) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

type SkillActionCommand struct {
	Action               int32        `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	Direction            *Vector3Data `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	TargetId             string       `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SkillActionCommand) Reset()         { *m = SkillActionCommand{} }
func (m *SkillActionCommand) String() string { return proto.CompactTextString(m) }
func (*SkillActionCommand) ProtoMessage()    {}
func (*SkillActionCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6a5f28d4a278e7, []int{5}
}
func (m *SkillActionCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillActionCommand.Unmarshal(m, b)
}
func (m *SkillActionCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillActionCommand.Marshal(b, m, deterministic)
}
func (m *SkillActionCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillActionCommand.Merge(m, src)
}
func (m *SkillActionCommand) XXX_Size() int {
	return xxx_messageInfo_SkillActionCommand.Size(m)
}
func (m *SkillActionCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillActionCommand.DiscardUnknown(m)
}

var xxx_messageInfo_SkillActionCommand proto.InternalMessageInfo

func (m *SkillActionCommand) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *SkillActionCommand) GetDirection() *Vector3Data {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *SkillActionCommand) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func init() {
	proto.RegisterEnum("protoc.ROOM_STATUS_MSG_TYPE", ROOM_STATUS_MSG_TYPE_name, ROOM_STATUS_MSG_TYPE_value)
	proto.RegisterType((*UserData)(nil), "protoc.UserData")
	proto.RegisterType((*CurrentUsersData)(nil), "protoc.CurrentUsersData")
	proto.RegisterType((*CloseMicRequest)(nil), "protoc.CloseMicRequest")
	proto.RegisterType((*OpenMicRequest)(nil), "protoc.OpenMicRequest")
	proto.RegisterType((*SkillActionRequest)(nil), "protoc.SkillActionRequest")
	proto.RegisterType((*SkillActionCommand)(nil), "protoc.SkillActionCommand")
}

func init() { proto.RegisterFile("room_status.proto", fileDescriptor_6f6a5f28d4a278e7) }

var fileDescriptor_6f6a5f28d4a278e7 = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xbf, 0x6f, 0xd3, 0x4e,
	0x14, 0xff, 0xa6, 0x69, 0xfa, 0x4d, 0x5e, 0x04, 0x35, 0x47, 0xa9, 0xaf, 0xe1, 0x57, 0x94, 0x01,
	0x05, 0x86, 0x20, 0xda, 0xbf, 0xc0, 0x38, 0x06, 0x45, 0xc4, 0x71, 0xb9, 0x73, 0x90, 0x60, 0xc0,
	0x3a, 0xec, 0x0b, 0xb2, 0xb0, 0x7d, 0xc5, 0xbe, 0x50, 0x24, 0x16, 0x46, 0x66, 0xfe, 0x00, 0xfe,
	0x0f, 0x06, 0x16, 0x66, 0x66, 0x66, 0x16, 0x16, 0x66, 0x16, 0x16, 0x84, 0xee, 0xec, 0xa4, 0xa1,
	0x2d, 0x12, 0x13, 0x53, 0xde, 0xe7, 0xc7, 0x7b, 0xef, 0xde, 0xc7, 0x52, 0xe0, 0x5c, 0x2e, 0x44,
	0x1a, 0x14, 0x92, 0xc9, 0x79, 0x31, 0x38, 0xc8, 0x85, 0x14, 0x68, 0x43, 0xff, 0x84, 0x1d, 0x50,
	0x52, 0xc9, 0xf5, 0x5e, 0xaf, 0x41, 0x73, 0x5a, 0xf0, 0x7c, 0xc8, 0x24, 0x43, 0xdb, 0xb0, 0x31,
	0x2f, 0x78, 0x3e, 0x8a, 0x70, 0xad, 0x5b, 0xeb, 0xb7, 0x48, 0x85, 0x10, 0x82, 0xf5, 0x8c, 0xa5,
	0x1c, 0xaf, 0x69, 0x56, 0xd7, 0xe8, 0x12, 0xb4, 0x64, 0x9c, 0xf2, 0x42, 0xb2, 0xf4, 0x00, 0xd7,
	0xbb, 0xb5, 0x7e, 0x83, 0x1c, 0x11, 0xa8, 0x03, 0xcd, 0x99, 0x48, 0x12, 0x71, 0xc8, 0x23, 0xbc,
	0xde, 0xad, 0xf5, 0x9b, 0x64, 0x89, 0x91, 0x01, 0xf5, 0x34, 0x0e, 0x71, 0x43, 0xd3, 0xaa, 0x54,
	0x7b, 0xd9, 0x0b, 0x26, 0x59, 0x8e, 0x37, 0xca, 0xbd, 0x25, 0x52, 0x7c, 0xc2, 0x59, 0xc4, 0x73,
	0xfc, 0xbf, 0x36, 0x57, 0x48, 0xbd, 0xa7, 0xe0, 0xc9, 0x0c, 0x37, 0x35, 0xab, 0x6b, 0xe5, 0x15,
	0x59, 0x12, 0x67, 0x1c, 0xb7, 0x4a, 0x6f, 0x89, 0x50, 0x17, 0xda, 0x62, 0x36, 0x1b, 0xc7, 0x19,
	0xf7, 0xe3, 0x94, 0x63, 0xd0, 0x2f, 0x5d, 0xa5, 0x7a, 0x8f, 0xc1, 0xb0, 0xe7, 0x79, 0xce, 0x33,
	0xa9, 0x82, 0x28, 0x74, 0x12, 0xd7, 0xa0, 0xa1, 0x6e, 0x2f, 0x70, 0xad, 0x5b, 0xef, 0xb7, 0x77,
	0x8d, 0x32, 0xad, 0x70, 0xb0, 0x88, 0x8a, 0x94, 0xb2, 0xbe, 0x85, 0xbd, 0xd4, 0xc1, 0x34, 0x88,
	0x2a, 0x15, 0x93, 0x89, 0xc3, 0x2a, 0x11, 0x55, 0xf6, 0xae, 0xc3, 0xa6, 0x9d, 0x88, 0x82, 0xbb,
	0x71, 0x48, 0xf8, 0xf3, 0x39, 0x2f, 0xe4, 0x9f, 0x82, 0xee, 0xf5, 0xe1, 0xac, 0x77, 0xc0, 0xb3,
	0xbf, 0x70, 0xbe, 0x02, 0x44, 0x9f, 0xc5, 0x49, 0x62, 0x85, 0x32, 0x16, 0xd9, 0x8a, 0x9b, 0x69,
	0x42, 0xbb, 0x1b, 0xa4, 0x42, 0xe8, 0x16, 0xb4, 0xa2, 0x38, 0xe7, 0xa5, 0xa4, 0x1e, 0xdb, 0xde,
	0x3d, 0xbf, 0x38, 0xe9, 0x01, 0x0f, 0xa5, 0xc8, 0xf7, 0xf4, 0x55, 0x47, 0x2e, 0xf5, 0x05, 0x25,
	0xcb, 0x9f, 0x72, 0x39, 0x8a, 0xf4, 0x31, 0x2d, 0xb2, 0xc4, 0xc7, 0x96, 0xdb, 0x22, 0x4d, 0x59,
	0x16, 0xfd, 0xa3, 0xe5, 0x37, 0xde, 0xd5, 0x61, 0x8b, 0x78, 0x9e, 0x1b, 0x50, 0xdf, 0xf2, 0xa7,
	0x34, 0x70, 0xe9, 0xdd, 0xc0, 0x7f, 0xb8, 0xef, 0xa0, 0x4d, 0x68, 0x13, 0xea, 0x06, 0x43, 0xe7,
	0x8e, 0x35, 0x1d, 0xfb, 0xc6, 0x7f, 0xe8, 0x0a, 0xec, 0x28, 0xc2, 0x9e, 0x12, 0xe2, 0x4c, 0xfc,
	0x60, 0x4a, 0x1d, 0x42, 0x03, 0xe2, 0xdc, 0x9f, 0x3a, 0xd4, 0x37, 0xde, 0x9b, 0xe8, 0x2a, 0x74,
	0x4e, 0xd3, 0xe9, 0xbe, 0x37, 0xa1, 0x8e, 0xf1, 0xc1, 0x44, 0x08, 0xce, 0x28, 0x83, 0x12, 0x82,
	0xa1, 0xe5, 0x5b, 0xc6, 0x47, 0x13, 0x5d, 0x84, 0xed, 0x93, 0x4d, 0x5a, 0xfc, 0x64, 0xa2, 0x0e,
	0x5c, 0xd0, 0xe2, 0xd8, 0xa3, 0x4e, 0xe0, 0x8e, 0xec, 0xe5, 0xb6, 0xcf, 0x47, 0x8d, 0x2b, 0x5a,
	0xb5, 0xe9, 0xcb, 0x29, 0x8d, 0xb6, 0xe7, 0xba, 0xd6, 0x64, 0x68, 0x7c, 0x35, 0xd1, 0x0e, 0x6c,
	0x29, 0xcd, 0xdb, 0x77, 0x26, 0xbf, 0xcd, 0xfc, 0xb6, 0x6c, 0x5b, 0x91, 0xaa, 0x91, 0xdf, 0x4f,
	0xb6, 0x2d, 0x26, 0xfe, 0x30, 0xd1, 0x65, 0xc0, 0x4a, 0xa2, 0xf7, 0x46, 0xe3, 0x71, 0x60, 0xd9,
	0xfe, 0xc8, 0x9b, 0x2c, 0xa7, 0xfe, 0x34, 0x17, 0xb9, 0x1d, 0x93, 0xab, 0xc9, 0x6f, 0xf0, 0xa9,
	0xed, 0x8b, 0xe9, 0x6f, 0xf1, 0xed, 0xf6, 0xa3, 0xd6, 0x60, 0x70, 0xb3, 0xfc, 0xc0, 0x4f, 0xca,
	0xff, 0x9c, 0xbd, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x45, 0xcd, 0xab, 0x8f, 0x04, 0x00,
	0x00,
}
