// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: room_event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protoc {

  /// <summary>Holder for reflection information generated from room_event.proto</summary>
  public static partial class RoomEventReflection {

    #region Descriptor
    /// <summary>File descriptor for room_event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RoomEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChByb29tX2V2ZW50LnByb3RvEgZwcm90b2MivwIKC1VzZXJFbGVtZW50EhcK",
            "D2ltZWlfaG1hY3NoYTI1NhgBIAEoCRISCgpwZXJzb25hX2lkGAIgASgJEg0K",
            "BXVwX2lkGAMgASgJEg4KBmdlbmRlchgEIAEoCRILCgNhZ2UYBSABKAkSEQoJ",
            "cmVzaWRlbmNlGAYgASgJEhYKDnJlc2lkZW5jZV9jaXR5GAcgASgJEhsKE3Vw",
            "X2NvbnN0ZWxsYXRpb25fdXAYCCABKAkSFwoPYWN0aXZlX2RhdGVfZGV2GAkg",
            "ASgJEhkKEWluYWN0aXZlX2RhdGVfZGV2GAogASgJEg4KBmNwX2RldhgLIAEo",
            "CRIRCglicmFuZF9kZXYYDCABKAkSCgoCb3MYDSABKAkSFwoPYW5kcm9pZF92",
            "ZXJfZGV2GA4gASgJEhMKC2lvc192ZXJfZGV2GA8gASgJIt0BCg1BY3Rpb25F",
            "bGVtZW50EgsKA3VpZBgBIAEoCRIRCgl1c2VyX2NpdHkYAiABKAkSDwoHaXRl",
            "bV9pZBgDIAEoCRIRCglhdXRob3JfaWQYBCABKAkSEQoJaXRlbV9jaXR5GAUg",
            "ASgJEg8KB2NoYW5uZWwYBiABKAkSEQoJaXRlbV9jYXRlGAcgASgJEg4KBmZp",
            "bmlzaBgIIAEoCRIMCgRsaWtlGAkgASgJEg4KBmRldmljZRgKIAEoCRIMCgR0",
            "aW1lGAsgASgJEhUKDWR1cmF0aW9uX3RpbWUYDCABKAlCC1oJLi4vcHJvdG9j",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protoc.UserElement), global::Protoc.UserElement.Parser, new[]{ "ImeiHmacsha256", "PersonaId", "UpId", "Gender", "Age", "Residence", "ResidenceCity", "UpConstellationUp", "ActiveDateDev", "InactiveDateDev", "CpDev", "BrandDev", "Os", "AndroidVerDev", "IosVerDev" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protoc.ActionElement), global::Protoc.ActionElement.Parser, new[]{ "Uid", "UserCity", "ItemId", "AuthorId", "ItemCity", "Channel", "ItemCate", "Finish", "Like", "Device", "Time", "DurationTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UserElement : pb::IMessage<UserElement>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserElement> _parser = new pb::MessageParser<UserElement>(() => new UserElement());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserElement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protoc.RoomEventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserElement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserElement(UserElement other) : this() {
      imeiHmacsha256_ = other.imeiHmacsha256_;
      personaId_ = other.personaId_;
      upId_ = other.upId_;
      gender_ = other.gender_;
      age_ = other.age_;
      residence_ = other.residence_;
      residenceCity_ = other.residenceCity_;
      upConstellationUp_ = other.upConstellationUp_;
      activeDateDev_ = other.activeDateDev_;
      inactiveDateDev_ = other.inactiveDateDev_;
      cpDev_ = other.cpDev_;
      brandDev_ = other.brandDev_;
      os_ = other.os_;
      androidVerDev_ = other.androidVerDev_;
      iosVerDev_ = other.iosVerDev_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserElement Clone() {
      return new UserElement(this);
    }

    /// <summary>Field number for the "imei_hmacsha256" field.</summary>
    public const int ImeiHmacsha256FieldNumber = 1;
    private string imeiHmacsha256_ = "";
    /// <summary>
    ///hmacsha256 加密的最优 imei
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImeiHmacsha256 {
      get { return imeiHmacsha256_; }
      set {
        imeiHmacsha256_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "persona_id" field.</summary>
    public const int PersonaIdFieldNumber = 2;
    private string personaId_ = "";
    /// <summary>
    ///hmacsha256 加密的最优 imei
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PersonaId {
      get { return personaId_; }
      set {
        personaId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "up_id" field.</summary>
    public const int UpIdFieldNumber = 3;
    private string upId_ = "";
    /// <summary>
    ///设备唯一号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UpId {
      get { return upId_; }
      set {
        upId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 4;
    private string gender_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Gender {
      get { return gender_; }
      set {
        gender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 5;
    private string age_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Age {
      get { return age_; }
      set {
        age_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "residence" field.</summary>
    public const int ResidenceFieldNumber = 6;
    private string residence_ = "";
    /// <summary>
    ///常驻省份（湖南省、广东省。。。）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Residence {
      get { return residence_; }
      set {
        residence_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "residence_city" field.</summary>
    public const int ResidenceCityFieldNumber = 7;
    private string residenceCity_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResidenceCity {
      get { return residenceCity_; }
      set {
        residenceCity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "up_constellation_up" field.</summary>
    public const int UpConstellationUpFieldNumber = 8;
    private string upConstellationUp_ = "";
    /// <summary>
    ///星座（金牛座、白羊座。。。）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UpConstellationUp {
      get { return upConstellationUp_; }
      set {
        upConstellationUp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "active_date_dev" field.</summary>
    public const int ActiveDateDevFieldNumber = 9;
    private string activeDateDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ActiveDateDev {
      get { return activeDateDev_; }
      set {
        activeDateDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inactive_date_dev" field.</summary>
    public const int InactiveDateDevFieldNumber = 10;
    private string inactiveDateDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InactiveDateDev {
      get { return inactiveDateDev_; }
      set {
        inactiveDateDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cp_dev" field.</summary>
    public const int CpDevFieldNumber = 11;
    private string cpDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CpDev {
      get { return cpDev_; }
      set {
        cpDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "brand_dev" field.</summary>
    public const int BrandDevFieldNumber = 12;
    private string brandDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BrandDev {
      get { return brandDev_; }
      set {
        brandDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "os" field.</summary>
    public const int OsFieldNumber = 13;
    private string os_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Os {
      get { return os_; }
      set {
        os_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "android_ver_dev" field.</summary>
    public const int AndroidVerDevFieldNumber = 14;
    private string androidVerDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AndroidVerDev {
      get { return androidVerDev_; }
      set {
        androidVerDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ios_ver_dev" field.</summary>
    public const int IosVerDevFieldNumber = 15;
    private string iosVerDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IosVerDev {
      get { return iosVerDev_; }
      set {
        iosVerDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserElement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserElement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ImeiHmacsha256 != other.ImeiHmacsha256) return false;
      if (PersonaId != other.PersonaId) return false;
      if (UpId != other.UpId) return false;
      if (Gender != other.Gender) return false;
      if (Age != other.Age) return false;
      if (Residence != other.Residence) return false;
      if (ResidenceCity != other.ResidenceCity) return false;
      if (UpConstellationUp != other.UpConstellationUp) return false;
      if (ActiveDateDev != other.ActiveDateDev) return false;
      if (InactiveDateDev != other.InactiveDateDev) return false;
      if (CpDev != other.CpDev) return false;
      if (BrandDev != other.BrandDev) return false;
      if (Os != other.Os) return false;
      if (AndroidVerDev != other.AndroidVerDev) return false;
      if (IosVerDev != other.IosVerDev) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ImeiHmacsha256.Length != 0) hash ^= ImeiHmacsha256.GetHashCode();
      if (PersonaId.Length != 0) hash ^= PersonaId.GetHashCode();
      if (UpId.Length != 0) hash ^= UpId.GetHashCode();
      if (Gender.Length != 0) hash ^= Gender.GetHashCode();
      if (Age.Length != 0) hash ^= Age.GetHashCode();
      if (Residence.Length != 0) hash ^= Residence.GetHashCode();
      if (ResidenceCity.Length != 0) hash ^= ResidenceCity.GetHashCode();
      if (UpConstellationUp.Length != 0) hash ^= UpConstellationUp.GetHashCode();
      if (ActiveDateDev.Length != 0) hash ^= ActiveDateDev.GetHashCode();
      if (InactiveDateDev.Length != 0) hash ^= InactiveDateDev.GetHashCode();
      if (CpDev.Length != 0) hash ^= CpDev.GetHashCode();
      if (BrandDev.Length != 0) hash ^= BrandDev.GetHashCode();
      if (Os.Length != 0) hash ^= Os.GetHashCode();
      if (AndroidVerDev.Length != 0) hash ^= AndroidVerDev.GetHashCode();
      if (IosVerDev.Length != 0) hash ^= IosVerDev.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ImeiHmacsha256.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImeiHmacsha256);
      }
      if (PersonaId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PersonaId);
      }
      if (UpId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UpId);
      }
      if (Gender.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Gender);
      }
      if (Age.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Age);
      }
      if (Residence.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Residence);
      }
      if (ResidenceCity.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ResidenceCity);
      }
      if (UpConstellationUp.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(UpConstellationUp);
      }
      if (ActiveDateDev.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ActiveDateDev);
      }
      if (InactiveDateDev.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(InactiveDateDev);
      }
      if (CpDev.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CpDev);
      }
      if (BrandDev.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(BrandDev);
      }
      if (Os.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Os);
      }
      if (AndroidVerDev.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(AndroidVerDev);
      }
      if (IosVerDev.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(IosVerDev);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ImeiHmacsha256.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImeiHmacsha256);
      }
      if (PersonaId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PersonaId);
      }
      if (UpId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UpId);
      }
      if (Gender.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Gender);
      }
      if (Age.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Age);
      }
      if (Residence.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Residence);
      }
      if (ResidenceCity.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ResidenceCity);
      }
      if (UpConstellationUp.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(UpConstellationUp);
      }
      if (ActiveDateDev.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ActiveDateDev);
      }
      if (InactiveDateDev.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(InactiveDateDev);
      }
      if (CpDev.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CpDev);
      }
      if (BrandDev.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(BrandDev);
      }
      if (Os.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Os);
      }
      if (AndroidVerDev.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(AndroidVerDev);
      }
      if (IosVerDev.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(IosVerDev);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ImeiHmacsha256.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImeiHmacsha256);
      }
      if (PersonaId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PersonaId);
      }
      if (UpId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UpId);
      }
      if (Gender.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Gender);
      }
      if (Age.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Age);
      }
      if (Residence.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Residence);
      }
      if (ResidenceCity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResidenceCity);
      }
      if (UpConstellationUp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UpConstellationUp);
      }
      if (ActiveDateDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActiveDateDev);
      }
      if (InactiveDateDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InactiveDateDev);
      }
      if (CpDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CpDev);
      }
      if (BrandDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BrandDev);
      }
      if (Os.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Os);
      }
      if (AndroidVerDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AndroidVerDev);
      }
      if (IosVerDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IosVerDev);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserElement other) {
      if (other == null) {
        return;
      }
      if (other.ImeiHmacsha256.Length != 0) {
        ImeiHmacsha256 = other.ImeiHmacsha256;
      }
      if (other.PersonaId.Length != 0) {
        PersonaId = other.PersonaId;
      }
      if (other.UpId.Length != 0) {
        UpId = other.UpId;
      }
      if (other.Gender.Length != 0) {
        Gender = other.Gender;
      }
      if (other.Age.Length != 0) {
        Age = other.Age;
      }
      if (other.Residence.Length != 0) {
        Residence = other.Residence;
      }
      if (other.ResidenceCity.Length != 0) {
        ResidenceCity = other.ResidenceCity;
      }
      if (other.UpConstellationUp.Length != 0) {
        UpConstellationUp = other.UpConstellationUp;
      }
      if (other.ActiveDateDev.Length != 0) {
        ActiveDateDev = other.ActiveDateDev;
      }
      if (other.InactiveDateDev.Length != 0) {
        InactiveDateDev = other.InactiveDateDev;
      }
      if (other.CpDev.Length != 0) {
        CpDev = other.CpDev;
      }
      if (other.BrandDev.Length != 0) {
        BrandDev = other.BrandDev;
      }
      if (other.Os.Length != 0) {
        Os = other.Os;
      }
      if (other.AndroidVerDev.Length != 0) {
        AndroidVerDev = other.AndroidVerDev;
      }
      if (other.IosVerDev.Length != 0) {
        IosVerDev = other.IosVerDev;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ImeiHmacsha256 = input.ReadString();
            break;
          }
          case 18: {
            PersonaId = input.ReadString();
            break;
          }
          case 26: {
            UpId = input.ReadString();
            break;
          }
          case 34: {
            Gender = input.ReadString();
            break;
          }
          case 42: {
            Age = input.ReadString();
            break;
          }
          case 50: {
            Residence = input.ReadString();
            break;
          }
          case 58: {
            ResidenceCity = input.ReadString();
            break;
          }
          case 66: {
            UpConstellationUp = input.ReadString();
            break;
          }
          case 74: {
            ActiveDateDev = input.ReadString();
            break;
          }
          case 82: {
            InactiveDateDev = input.ReadString();
            break;
          }
          case 90: {
            CpDev = input.ReadString();
            break;
          }
          case 98: {
            BrandDev = input.ReadString();
            break;
          }
          case 106: {
            Os = input.ReadString();
            break;
          }
          case 114: {
            AndroidVerDev = input.ReadString();
            break;
          }
          case 122: {
            IosVerDev = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ImeiHmacsha256 = input.ReadString();
            break;
          }
          case 18: {
            PersonaId = input.ReadString();
            break;
          }
          case 26: {
            UpId = input.ReadString();
            break;
          }
          case 34: {
            Gender = input.ReadString();
            break;
          }
          case 42: {
            Age = input.ReadString();
            break;
          }
          case 50: {
            Residence = input.ReadString();
            break;
          }
          case 58: {
            ResidenceCity = input.ReadString();
            break;
          }
          case 66: {
            UpConstellationUp = input.ReadString();
            break;
          }
          case 74: {
            ActiveDateDev = input.ReadString();
            break;
          }
          case 82: {
            InactiveDateDev = input.ReadString();
            break;
          }
          case 90: {
            CpDev = input.ReadString();
            break;
          }
          case 98: {
            BrandDev = input.ReadString();
            break;
          }
          case 106: {
            Os = input.ReadString();
            break;
          }
          case 114: {
            AndroidVerDev = input.ReadString();
            break;
          }
          case 122: {
            IosVerDev = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActionElement : pb::IMessage<ActionElement>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionElement> _parser = new pb::MessageParser<ActionElement>(() => new ActionElement());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionElement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protoc.RoomEventReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionElement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionElement(ActionElement other) : this() {
      uid_ = other.uid_;
      userCity_ = other.userCity_;
      itemId_ = other.itemId_;
      authorId_ = other.authorId_;
      itemCity_ = other.itemCity_;
      channel_ = other.channel_;
      itemCate_ = other.itemCate_;
      finish_ = other.finish_;
      like_ = other.like_;
      device_ = other.device_;
      time_ = other.time_;
      durationTime_ = other.durationTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionElement Clone() {
      return new ActionElement(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private string uid_ = "";
    /// <summary>
    ///用户 id,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_city" field.</summary>
    public const int UserCityFieldNumber = 2;
    private string userCity_ = "";
    /// <summary>
    /// 用户所在城市，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserCity {
      get { return userCity_; }
      set {
        userCity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 3;
    private string itemId_ = "";
    /// <summary>
    /// 作品 id,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ItemId {
      get { return itemId_; }
      set {
        itemId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "author_id" field.</summary>
    public const int AuthorIdFieldNumber = 4;
    private string authorId_ = "";
    /// <summary>
    ///作者 id,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AuthorId {
      get { return authorId_; }
      set {
        authorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_city" field.</summary>
    public const int ItemCityFieldNumber = 5;
    private string itemCity_ = "";
    /// <summary>
    ///作者城市，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ItemCity {
      get { return itemCity_; }
      set {
        itemCity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 6;
    private string channel_ = "";
    /// <summary>
    ///观看到该作品的来源，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Channel {
      get { return channel_; }
      set {
        channel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_cate" field.</summary>
    public const int ItemCateFieldNumber = 7;
    private string itemCate_ = "";
    /// <summary>
    ///作品类别，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ItemCate {
      get { return itemCate_; }
      set {
        itemCate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "finish" field.</summary>
    public const int FinishFieldNumber = 8;
    private string finish_ = "";
    /// <summary>
    ///是否浏览完作品，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Finish {
      get { return finish_; }
      set {
        finish_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "like" field.</summary>
    public const int LikeFieldNumber = 9;
    private string like_ = "";
    /// <summary>
    ///是否对作品点赞，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Like {
      get { return like_; }
      set {
        like_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device" field.</summary>
    public const int DeviceFieldNumber = 10;
    private string device_ = "";
    /// <summary>
    ///设备 id,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Device {
      get { return device_; }
      set {
        device_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 11;
    private string time_ = "";
    /// <summary>
    ///（track1:作品观看起始时间，track2:作品发布时间），
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Time {
      get { return time_; }
      set {
        time_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "duration_time" field.</summary>
    public const int DurationTimeFieldNumber = 12;
    private string durationTime_ = "";
    /// <summary>
    ///作品时长
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DurationTime {
      get { return durationTime_; }
      set {
        durationTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionElement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionElement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (UserCity != other.UserCity) return false;
      if (ItemId != other.ItemId) return false;
      if (AuthorId != other.AuthorId) return false;
      if (ItemCity != other.ItemCity) return false;
      if (Channel != other.Channel) return false;
      if (ItemCate != other.ItemCate) return false;
      if (Finish != other.Finish) return false;
      if (Like != other.Like) return false;
      if (Device != other.Device) return false;
      if (Time != other.Time) return false;
      if (DurationTime != other.DurationTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (UserCity.Length != 0) hash ^= UserCity.GetHashCode();
      if (ItemId.Length != 0) hash ^= ItemId.GetHashCode();
      if (AuthorId.Length != 0) hash ^= AuthorId.GetHashCode();
      if (ItemCity.Length != 0) hash ^= ItemCity.GetHashCode();
      if (Channel.Length != 0) hash ^= Channel.GetHashCode();
      if (ItemCate.Length != 0) hash ^= ItemCate.GetHashCode();
      if (Finish.Length != 0) hash ^= Finish.GetHashCode();
      if (Like.Length != 0) hash ^= Like.GetHashCode();
      if (Device.Length != 0) hash ^= Device.GetHashCode();
      if (Time.Length != 0) hash ^= Time.GetHashCode();
      if (DurationTime.Length != 0) hash ^= DurationTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uid);
      }
      if (UserCity.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserCity);
      }
      if (ItemId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ItemId);
      }
      if (AuthorId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AuthorId);
      }
      if (ItemCity.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ItemCity);
      }
      if (Channel.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Channel);
      }
      if (ItemCate.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ItemCate);
      }
      if (Finish.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Finish);
      }
      if (Like.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Like);
      }
      if (Device.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Device);
      }
      if (Time.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Time);
      }
      if (DurationTime.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(DurationTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uid);
      }
      if (UserCity.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserCity);
      }
      if (ItemId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ItemId);
      }
      if (AuthorId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AuthorId);
      }
      if (ItemCity.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ItemCity);
      }
      if (Channel.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Channel);
      }
      if (ItemCate.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ItemCate);
      }
      if (Finish.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Finish);
      }
      if (Like.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Like);
      }
      if (Device.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Device);
      }
      if (Time.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Time);
      }
      if (DurationTime.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(DurationTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (UserCity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserCity);
      }
      if (ItemId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemId);
      }
      if (AuthorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthorId);
      }
      if (ItemCity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemCity);
      }
      if (Channel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Channel);
      }
      if (ItemCate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemCate);
      }
      if (Finish.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Finish);
      }
      if (Like.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Like);
      }
      if (Device.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Device);
      }
      if (Time.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Time);
      }
      if (DurationTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DurationTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionElement other) {
      if (other == null) {
        return;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.UserCity.Length != 0) {
        UserCity = other.UserCity;
      }
      if (other.ItemId.Length != 0) {
        ItemId = other.ItemId;
      }
      if (other.AuthorId.Length != 0) {
        AuthorId = other.AuthorId;
      }
      if (other.ItemCity.Length != 0) {
        ItemCity = other.ItemCity;
      }
      if (other.Channel.Length != 0) {
        Channel = other.Channel;
      }
      if (other.ItemCate.Length != 0) {
        ItemCate = other.ItemCate;
      }
      if (other.Finish.Length != 0) {
        Finish = other.Finish;
      }
      if (other.Like.Length != 0) {
        Like = other.Like;
      }
      if (other.Device.Length != 0) {
        Device = other.Device;
      }
      if (other.Time.Length != 0) {
        Time = other.Time;
      }
      if (other.DurationTime.Length != 0) {
        DurationTime = other.DurationTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uid = input.ReadString();
            break;
          }
          case 18: {
            UserCity = input.ReadString();
            break;
          }
          case 26: {
            ItemId = input.ReadString();
            break;
          }
          case 34: {
            AuthorId = input.ReadString();
            break;
          }
          case 42: {
            ItemCity = input.ReadString();
            break;
          }
          case 50: {
            Channel = input.ReadString();
            break;
          }
          case 58: {
            ItemCate = input.ReadString();
            break;
          }
          case 66: {
            Finish = input.ReadString();
            break;
          }
          case 74: {
            Like = input.ReadString();
            break;
          }
          case 82: {
            Device = input.ReadString();
            break;
          }
          case 90: {
            Time = input.ReadString();
            break;
          }
          case 98: {
            DurationTime = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Uid = input.ReadString();
            break;
          }
          case 18: {
            UserCity = input.ReadString();
            break;
          }
          case 26: {
            ItemId = input.ReadString();
            break;
          }
          case 34: {
            AuthorId = input.ReadString();
            break;
          }
          case 42: {
            ItemCity = input.ReadString();
            break;
          }
          case 50: {
            Channel = input.ReadString();
            break;
          }
          case 58: {
            ItemCate = input.ReadString();
            break;
          }
          case 66: {
            Finish = input.ReadString();
            break;
          }
          case 74: {
            Like = input.ReadString();
            break;
          }
          case 82: {
            Device = input.ReadString();
            break;
          }
          case 90: {
            Time = input.ReadString();
            break;
          }
          case 98: {
            DurationTime = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
